using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Pixeval.Extensions.Generator;

internal static class PythonEmitter
{
    private static readonly HashSet<string> _PythonKeywords = new(StringComparer.Ordinal)
    {
        "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
        "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
        "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
        "with", "yield", "match", "case"
    };

    public static string EmitCommon(PidlModel model)
    {
        var context = new PythonModelContext(model);
        var builder = new StringBuilder();
        _ = builder.AppendLine(
            """
            # <auto-generated />
            from __future__ import annotations

            from enum import IntEnum

            from ._runtime import *

            """);
        AppendEnums(builder, model);
        AppendIids(builder, context);
        AppendInterfaceMetadata(builder, context);
        return builder.ToString();
    }

    public static string EmitSdk(PidlModel model)
    {
        var context = new PythonModelContext(model);
        var builder = new StringBuilder();
        _ = builder.AppendLine(
            """
                # <auto-generated />
                from __future__ import annotations

                import ctypes
                from collections.abc import Sequence

                from . import abi as _abi
                from ._sdk_runtime import *
                from .symbols import Symbol

                SDK_VERSION = "{{SDK_VERSION}}"

                """.Replace("{{SDK_VERSION}}", model.SdkVersion, StringComparison.Ordinal));
        AppendGeneratedSdkRuntime(builder, context, model);
        AppendSdkExports(builder, model);
        AppendSdkPresetManifest(builder, model);
        return builder.ToString();
    }

    private static void AppendEnums(StringBuilder builder, PidlModel model)
    {
        foreach (var definition in model.Enums)
        {
            _ = builder.AppendLine($"class {ShortName(definition.FullName)}(IntEnum):");
            var nextValue = 0;
            foreach (var value in definition.Values)
            {
                var actualValue = value.Value ?? nextValue.ToString();
                _ = builder.AppendLine($"    {PythonIdentifier(value.Name)} = {actualValue}");
                if (int.TryParse(actualValue, out var parsed))
                    nextValue = parsed + 1;
                else
                    ++nextValue;
            }

            _ = builder.AppendLine(
                """


                """);
        }
    }

    private static void AppendIids(StringBuilder builder, PythonModelContext context)
    {
        _ = builder.AppendLine("IID_IUNKNOWN = Guid.parse(\"00000000-0000-0000-C000-000000000046\")");
        foreach (var definition in context.InterfacesWithGuid)
            _ = builder.AppendLine($"IID_{ConstantName(definition)} = Guid.parse(\"{definition.Guid}\")");
        _ = builder.AppendLine(
            """


            """);
    }

    private static void AppendInterfaceMetadata(StringBuilder builder, PythonModelContext context)
    {
        _ = builder.AppendLine(
            "INTERFACE_IIDS = {");
        foreach (var definition in context.InterfacesWithGuid)
        {
            _ = builder.AppendLine($"    \"{ShortName(definition.FullName)}\": IID_{ConstantName(definition)},");
        }

        _ = builder.AppendLine(
            """
            }

            INTERFACE_CHAINS = {
            """);
        foreach (var definition in context.InterfacesWithGuid)
        {
            var chain = context.FlattenInterfaces(definition)
                .Where(static value => value.Guid is not null)
                .Select(static value => $"\"{ShortName(value.FullName)}\"");
            _ = builder.AppendLine($"    \"{ShortName(definition.FullName)}\": [{string.Join(", ", chain)}],");
        }

        _ = builder.AppendLine(
            """
            }

            INTERFACE_SLOTS = {
            """);
        foreach (var definition in context.InterfacesWithGuid)
        {
            _ = builder.AppendLine($"    \"{ShortName(definition.FullName)}\": {{");
            var slot = 3;
            foreach (var method in context.FlattenMethods(definition))
            {
                _ = builder.AppendLine($"        \"{ShortName(method.Owner.FullName)}.{method.Method.Name}\": {slot++},");
            }

            _ = builder.AppendLine("    },");
        }
        _ = builder.AppendLine(
            """
            }


            """);
    }

    private static void AppendGeneratedSdkRuntime(StringBuilder builder, PythonModelContext context, PidlModel model)
    {
        foreach (var definition in OrderPythonSdkDefinitions(context, model))
            AppendPythonSdkClass(builder, context, model.Metadata, definition);

        foreach (var definition in model.Interfaces.Where(static definition => definition.SdkName is not null))
        {
            var alias = definition.SdkName!;
            var className = PythonSdkClassName(definition);
            if (alias != className)
                _ = builder.AppendLine($"{alias} = {className}");
        }
    }

    private static void AppendSdkExports(StringBuilder builder, PidlModel model)
    {
        var exports = new SortedSet<string>(StringComparer.Ordinal)
        {
            "SDK_VERSION",
            "EntryMetadata",
            "read_icon"
        };

        foreach (var definition in model.Interfaces.Where(static definition => definition.SdkName is not null))
        {
            _ = exports.Add(PythonSdkClassName(definition));
            _ = exports.Add(definition.SdkName!);
        }

        _ = builder.AppendLine("__all__ = [");
        foreach (var export in exports)
            _ = builder.AppendLine($"    \"{export}\",");
        _ = builder.AppendLine(
            """
            ]

            """);
    }

    private static void AppendPythonSdkClass(StringBuilder builder, PythonModelContext context, PidlMetadata metadata, InterfaceDefinition definition)
    {
        var className = PythonSdkClassName(definition);
        var baseInterface = context.ResolveSdkBaseInterface(definition);
        var baseClass = baseInterface is null ? "SdkComObject" : PythonSdkClassName(baseInterface);
        var methodChain = context.FlattenMethods(definition);
        var inheritedInterfaces = baseInterface is null
            ? []
            : context.FlattenInterfaces(baseInterface).ToHashSet();
        var ownMethods = methodChain.Where(method => !inheritedInterfaces.Contains(method.Owner)).ToList();
        var concreteInterfaces = context.FlattenInterfaces(definition).Where(static value => value.Guid is not null).ToList();

        _ = builder.AppendLine($"class {className}({baseClass}):");
        if (ShortName(definition.FullName) is "IExtension")
        {
            AppendPythonRootExtension(builder, metadata, ownMethods, concreteInterfaces);
            return;
        }

        if (ShortName(definition.FullName) is "IExtensionsHost")
        {
            AppendPythonExtensionsHost(builder, metadata, ownMethods, concreteInterfaces);
            return;
        }

        if (definition.Attributes.Any(static attribute => attribute.Name is "sdkAbstract") && ownMethods.Count is 0)
        {
            AppendPythonAbstractPass(builder);
            return;
        }

        if (IsConcreteSettingsInterface(context, definition, out var settingsType))
        {
            AppendPythonConcreteSetting(builder, context, metadata, definition, ownMethods, concreteInterfaces, settingsType);
            return;
        }

        if (definition.Attributes.Any(static attribute => attribute.Name is "sdkAbstract"))
        {
            AppendPythonAbstractExtension(builder, context, metadata, definition, baseInterface, ownMethods, concreteInterfaces);
            return;
        }

        AppendPythonConcreteExtension(builder, context, metadata, definition, ownMethods, concreteInterfaces);
    }

    private static void AppendPythonAbstractPass(StringBuilder builder)
    {
        _ = builder.AppendLine(
            """
                pass

            """);
    }

    private static void AppendPythonRootExtension(
        StringBuilder builder,
        PidlMetadata metadata,
        IReadOnlyList<MethodWithOwner> ownMethods,
        IReadOnlyList<InterfaceDefinition> concreteInterfaces)
    {
        _ = builder.AppendLine(
            """
                def __init__(self, interfaces: _abi.InterfaceSet | None = None, extra_callbacks: Sequence[ctypes._CFuncPtr] = ()) -> None:
                    self.loaded = False
            """);
        AppendPythonCallbackList(builder, ownMethods, metadata, extendExtraCallbacks: true);
        _ = builder.AppendLine(
            $"""
                     super().__init__(
                         interfaces or _abi.InterfaceSet.of({PythonIidList(concreteInterfaces)}),
                         callbacks,
                     )
             """);

        foreach (var method in ownMethods.Where(static method => method.Method is { PropertyName: null, IsAsyncResultGetter: false }))
            AppendPythonExtensionMethod(builder, method, metadata, FindAsyncResultGetter(ownMethods, method.Method));
    }

    private static void AppendPythonExtensionsHost(
        StringBuilder builder,
        PidlMetadata metadata,
        IReadOnlyList<MethodWithOwner> ownMethods,
        IReadOnlyList<InterfaceDefinition> concreteInterfaces)
    {
        var fields = PythonFieldsForMethods(ownMethods)
            .Where(static field => field.Name is not "sdk_version" and not "extensions" and not "icon")
            .ToList();

        _ = builder.AppendLine(
            """
                def __init__(
                    self,
            """);
        if (fields.Count > 0)
            _ = builder.AppendLine("        *,");
        foreach (var field in fields)
            _ = builder.AppendLine($"        {field.Name}: {field.Annotation}{field.DefaultValue ?? ""},");
        _ = builder.AppendLine(
            """
                    icon: bytes | None = None,
                    sdk_version: str | None = None,
                ) -> None:
            """);
        foreach (var field in fields)
            _ = builder.AppendLine($"        self.{field.Name} = {field.Name}");
        _ = builder.AppendLine(
            """
                    self.icon = icon or b""
                    self.sdk_version = sdk_version or SDK_VERSION
                    self.extensions: list[_abi.ComObject] = []
                    self.culture_name = ""
                    self.temp_directory = ""
                    self.extension_directory = ""
                    self.logger_pointer = 0
            """);
        AppendPythonCallbackList(builder, ownMethods, metadata, extendExtraCallbacks: false);
        _ = builder.AppendLine(
            $"""
                     super().__init__(
                         _abi.InterfaceSet.of({PythonIidList(concreteInterfaces)}),
                         callbacks,
                     )

                 def add_extension(self, extension: _abi.ComObject) -> None:
                     self.extensions.append(extension)

                 def initialize(self) -> None:
                     pass
             """);

        AppendPythonHostInitializeMethod(builder);
        foreach (var method in ownMethods.Where(static method => method.Method.PropertyName is not null))
            AppendPythonPropertyDefault(builder, method);
    }

    private static void AppendPythonHostInitializeMethod(StringBuilder builder)
    {
        _ = builder.AppendLine(
            """
                def _initialize(self, _self: int, cultureName: int, tempDirectory: int, extensionDirectory: int, logger: int) -> int:
                    self.culture_name = _abi.read_utf16(cultureName)
                    self.temp_directory = _abi.read_utf16(tempDirectory)
                    self.extension_directory = _abi.read_utf16(extensionDirectory)
                    self.logger_pointer = int(logger or 0)
                    self.initialize()
                    return _abi.S_OK

            """);
    }

    private static void AppendPythonAbstractExtension(
        StringBuilder builder,
        PythonModelContext context,
        PidlMetadata metadata,
        InterfaceDefinition definition,
        InterfaceDefinition? baseInterface,
        IReadOnlyList<MethodWithOwner> ownMethods,
        IReadOnlyList<InterfaceDefinition> concreteInterfaces)
    {
        var shortName = ShortName(definition.FullName);
        switch (shortName)
        {
            case "IEntryExtension":
                AppendPythonEntryBase(builder, metadata, ownMethods, concreteInterfaces);
                return;
            case "ISettingsExtension":
                AppendPythonSettingsBase(builder, metadata, ownMethods, concreteInterfaces);
                return;
        }

        var ownFields = PythonFieldsForMethods(ownMethods)
            .Where(field => !IsMetadataBackedProperty(shortName, field.Name))
            .ToList();
        var fields = ownFields
            .GroupBy(static field => field.Name, StringComparer.Ordinal)
            .Select(static group => group.First())
            .ToList();
        var constructorParameters = shortName is "IFormatProviderExtension"
            ? PythonConstructorParameters(fields)
            : "";
        var usesEntryMetadata = context.FlattenInterfaces(definition).Any(static value => ShortName(value.FullName) is "IEntryExtension");

        _ = builder.AppendLine($"    def __init__(self{(usesEntryMetadata ? ", metadata: EntryMetadata" : "")}{constructorParameters}, interfaces: _abi.InterfaceSet | None = None, extra_callbacks: Sequence[ctypes._CFuncPtr] = ()) -> None:");
        foreach (var field in ownFields)
            _ = builder.AppendLine($"        self.{field.Name} = {field.Name}");
        AppendPythonCallbackList(builder, ownMethods, metadata, extendExtraCallbacks: true);
        if (usesEntryMetadata)
        {
            var arguments = new[]
            {
                "metadata",
                $"interfaces or _abi.InterfaceSet.of({PythonIidList(concreteInterfaces)})",
                "callbacks"
            };
            _ = builder.AppendLine(
                $"""
                         super().__init__(
                 {string.Join(Environment.NewLine, arguments.Select(static argument => $"            {argument},"))}
                         )
                 """);
        }
        else
        {
            _ = builder.AppendLine(
                $"""
                         super().__init__(
                             interfaces or _abi.InterfaceSet.of({PythonIidList(concreteInterfaces)}),
                             callbacks,
                         )
                 """);
        }

        foreach (var method in ownMethods.Where(static method => method.Method.PropertyName is not null))
            AppendPythonPropertyDefault(builder, method);
    }

    private static void AppendPythonEntryBase(
        StringBuilder builder,
        PidlMetadata metadata,
        IReadOnlyList<MethodWithOwner> ownMethods,
        IReadOnlyList<InterfaceDefinition> concreteInterfaces)
    {
        _ = builder.AppendLine(
            """
                def __init__(self, metadata: EntryMetadata, interfaces: _abi.InterfaceSet | None = None, extra_callbacks: Sequence[ctypes._CFuncPtr] = ()) -> None:
                    self.metadata = metadata
            """);
        AppendPythonCallbackList(builder, ownMethods, metadata, extendExtraCallbacks: true);
        _ = builder.AppendLine(
            $"""
                     super().__init__(
                         interfaces or _abi.InterfaceSet.of({PythonIidList(concreteInterfaces)}),
                         callbacks,
                     )
             """);

        foreach (var method in ownMethods.Where(static method => method.Method.PropertyName is not null))
            AppendPythonPropertyDefault(builder, method);
    }

    private static void AppendPythonSettingsBase(
        StringBuilder builder,
        PidlMetadata metadata,
        IReadOnlyList<MethodWithOwner> ownMethods,
        IReadOnlyList<InterfaceDefinition> concreteInterfaces)
    {
        _ = builder.AppendLine(
            """
                settings_type = _abi.SettingsType.String

                def __init__(self, metadata: EntryMetadata, extra_interfaces: Sequence[_abi.Guid] = (), extra_callbacks: Sequence[ctypes._CFuncPtr] = ()) -> None:
            """);
        AppendPythonCallbackList(builder, ownMethods, metadata, extendExtraCallbacks: true);
        _ = builder.AppendLine(
            $"""
                     super().__init__(
                         metadata,
                         _abi.InterfaceSet.of({PythonIidList(concreteInterfaces)}, *extra_interfaces),
                         callbacks,
                     )
             """);

        foreach (var method in ownMethods.Where(static method => method.Method.PropertyName is not null))
            AppendPythonPropertyDefault(builder, method);
    }

    private static void AppendPythonConcreteSetting(
        StringBuilder builder,
        PythonModelContext context,
        PidlMetadata metadata,
        InterfaceDefinition definition,
        IReadOnlyList<MethodWithOwner> ownMethods,
        IReadOnlyList<InterfaceDefinition> concreteInterfaces,
        string settingsType)
    {
        var extraInterfaces = context.FlattenInterfaces(definition)
            .Where(interfaceDefinition => interfaceDefinition.Guid is not null &&
                                          ShortName(interfaceDefinition.FullName) is not "IExtension" and not "IEntryExtension" and not "ISettingsExtension")
            .ToList();
        var fields = PythonFieldsForMethods(ownMethods);
        var constructorParameters = PythonConstructorParameters(fields);
        _ = builder.AppendLine(
            $"""
                settings_type = _abi.SettingsType.{settingsType}

                def __init__(self, metadata: EntryMetadata{constructorParameters}) -> None:
            """);
        foreach (var field in fields)
        {
            _ = builder.AppendLine($"        self.{field.Name} = {field.Name}");
            if (field.Name is "default_value")
                _ = builder.AppendLine($"        self.value = {field.Name}");
        }

        if (fields.All(static field => field.Name is not "default_value"))
            _ = builder.AppendLine("        self.value = None");

        _ = builder.AppendLine(
            $"""
                     super().__init__(
                         metadata,
                         [{string.Join(", ", extraInterfaces.Select(static value => "_abi.IID_" + ConstantName(value)))}],
                         [
             """);
        foreach (var method in ownMethods)
            _ = builder.AppendLine($"                {PythonCallbackExpression(method, "self", metadata)},");
        _ = builder.AppendLine(
            """
                        ],
                    )
            """);
        foreach (var method in ownMethods.Where(static method => method.Method is { Name: "OnValueChanged", DateTimeOffsetParameters.Count: 0 }))
            AppendPythonValueChangedMethods(builder, method, metadata);
        foreach (var method in ownMethods.Where(static method => method.Method.ReturnDictionary is not null))
            AppendPythonReturnDictionaryMethod(builder, method, metadata);
        var dateTimeOffsetGetter = ownMethods.FirstOrDefault(static method => method.Method.ReturnDateTimeOffset is not null)?.Method;
        var dateTimeOffsetChanged = ownMethods.FirstOrDefault(static method => method.Method.DateTimeOffsetParameters.Count > 0)?.Method;
        if (dateTimeOffsetGetter is not null || dateTimeOffsetChanged is not null)
            AppendPythonDateTimeOffsetMethods(builder, dateTimeOffsetGetter, dateTimeOffsetChanged, metadata);
    }

    private static void AppendPythonConcreteExtension(
        StringBuilder builder,
        PythonModelContext context,
        PidlMetadata metadata,
        InterfaceDefinition definition,
        IReadOnlyList<MethodWithOwner> ownMethods,
        IReadOnlyList<InterfaceDefinition> concreteInterfaces)
    {
        if (context.FlattenInterfaces(definition).Any(static value => ShortName(value.FullName) is "IEntryExtension"))
            AppendPythonEntryBackedExtension(builder, metadata, ownMethods, concreteInterfaces);
        else
            AppendPythonExtensionBackedExtension(builder, context, metadata, definition, ownMethods, concreteInterfaces);

        foreach (var method in ownMethods.Where(static method => method.Method is { PropertyName: null, IsAsyncResultGetter: false }))
            AppendPythonExtensionMethod(builder, method, metadata, FindAsyncResultGetter(ownMethods, method.Method));
        foreach (var method in ownMethods.Where(static method => method.Method.IsAsyncResultGetter))
            AppendPythonAsyncResultGetter(builder, method, metadata);
        foreach (var method in ownMethods.Where(static method => method.Method.PropertyName is not null))
            AppendPythonPropertyDefault(builder, method);
    }

    private static void AppendPythonEntryBackedExtension(
        StringBuilder builder,
        PidlMetadata metadata,
        IReadOnlyList<MethodWithOwner> ownMethods,
        IReadOnlyList<InterfaceDefinition> concreteInterfaces)
    {
        _ = builder.AppendLine("    def __init__(self, metadata: EntryMetadata, interfaces: _abi.InterfaceSet | None = None, extra_callbacks: Sequence[ctypes._CFuncPtr] = ()) -> None:");
        AppendPythonCallbackList(builder, ownMethods, metadata, extendExtraCallbacks: true);
        _ = builder.AppendLine(
            $"""
                     super().__init__(
                         metadata,
                         interfaces or _abi.InterfaceSet.of({PythonIidList(concreteInterfaces)}),
                         callbacks,
                     )
             """);
    }

    private static void AppendPythonExtensionBackedExtension(
        StringBuilder builder,
        PythonModelContext context,
        PidlMetadata metadata,
        InterfaceDefinition definition,
        IReadOnlyList<MethodWithOwner> ownMethods,
        IReadOnlyList<InterfaceDefinition> concreteInterfaces)
    {
        var shortName = ShortName(definition.FullName);
        var baseInterface = context.ResolveSdkBaseInterface(definition);
        var hasGeneratedBase = baseInterface is not null;
        var baseFields = hasGeneratedBase ? PythonConstructorFields(context, baseInterface!) : [];
        var ownFields = PythonFieldsForMethods(ownMethods);
        var fields = baseFields
            .Concat(ownFields)
            .GroupBy(static field => field.Name, StringComparer.Ordinal)
            .Select(static group => group.First())
            .ToList();
        var constructor = shortName is "IDownloaderExtension"
            ? ""
            : PythonConstructorParameters(fields) + (hasGeneratedBase
                ? ""
                : ", interfaces: _abi.InterfaceSet | None = None, extra_callbacks: Sequence[ctypes._CFuncPtr] = ()");

        _ = builder.AppendLine($"    def __init__(self{constructor}) -> None:");
        foreach (var field in ownFields)
            _ = builder.AppendLine($"        self.{field.Name} = {field.Name}");

        if (hasGeneratedBase)
        {
            var arguments = baseFields.Select(static field => field.Name)
                .Concat([
                    $"_abi.InterfaceSet.of({PythonIidList(concreteInterfaces)})"
                ])
                .ToList();

            _ = builder.AppendLine(
                $"""
                         super().__init__(
                 {string.Join(Environment.NewLine, arguments.Select(static argument => $"            {argument},"))}
                             [
                 """);
            foreach (var callback in ownMethods.Select(method => PythonCallbackExpression(method, "self", metadata)))
                _ = builder.AppendLine($"                {callback},");
            _ = builder.AppendLine(
                """
                            ],
                        )
                """);
            return;
        }

        var extendExtraCallbacks = shortName is not "IDownloaderExtension";
        if (extendExtraCallbacks)
        {
            AppendPythonCallbackList(builder, ownMethods, metadata, extendExtraCallbacks: true);
            _ = builder.AppendLine(
                $"""
                         super().__init__(
                             interfaces or _abi.InterfaceSet.of({PythonIidList(concreteInterfaces)}),
                             callbacks,
                         )
                 """);
            return;
        }

        _ = builder.AppendLine(
            $"""
                     super().__init__(
                         _abi.InterfaceSet.of({PythonIidList(concreteInterfaces)}),
                         [
             """);
        foreach (var callback in ownMethods.Select(method => PythonCallbackExpression(method, "self", metadata)))
            _ = builder.AppendLine($"                {callback},");
        _ = builder.AppendLine(
            """
                        ],
                    )
            """);
    }

    private static void AppendPythonCallbackList(
        StringBuilder builder,
        IReadOnlyList<MethodWithOwner> methods,
        PidlMetadata metadata,
        bool extendExtraCallbacks)
    {
        _ = builder.AppendLine(
            "        callbacks = [");
        foreach (var callback in methods.Select(method => PythonCallbackExpression(method, "self", metadata)))
        {
            _ = builder.AppendLine($"            {callback},");
        }

        _ = builder.AppendLine(
            "        ]");
        if (extendExtraCallbacks)
        {
            _ = builder.AppendLine(
                "        callbacks.extend(extra_callbacks)");
        }
    }

    private static string PythonCallbackExpression(MethodWithOwner method, string targetPrefix, PidlMetadata metadata)
    {
        var methodName = method.Method.Name;
        if (method.Method.PropertyName is not null)
            return PythonPropertyCallback(method, targetPrefix, metadata);

        var callbackType = PythonCallbackType(method.Method, metadata);
        var target = PythonPrivateMethodName(method.Method.Name);
        return $"{callbackType}({targetPrefix}.{target})";
    }

    private static string PythonPropertyCallback(MethodWithOwner method, string targetPrefix, PidlMetadata metadata)
    {
        var propertyName = ToSnakeCase(method.Method.PropertyName!);
        var propertySource = PythonPropertySource(method, targetPrefix, propertyName);
        if (method.Method.ReturnDictionary is not null)
            return $"{PythonCallbackType(method.Method, metadata)}({targetPrefix}.{PythonPrivateMethodName(method.Method.Name)})";

        if (method.Method.ReturnDateTimeOffset is not null)
            return $"_abi.CALLBACK(_abi.HRESULT, _abi.VOIDP, ctypes.POINTER(_abi.INT64), ctypes.POINTER(_abi.INT32))({targetPrefix}.{PythonPrivateMethodName(method.Method.Name)})";

        if (method.Method.ReturnArrayCountName is not null)
            return $"ArrayReturnCallback(lambda _self, returnCount, result: {PythonCopyArrayReturnValue(method.Method.ReturnType, propertySource, "returnCount", "result")})";

        return method.Method.ReturnType switch
        {
            "string" or "string?" => $"StringReturnCallback(lambda _self, result: _abi.copy_utf16({propertySource}, result))",
            "bool" => PythonBoolReturnCallback(metadata, propertySource),
            "int" => $"IntReturnCallback(lambda _self, result: _copy_int({propertySource}, result))",
            "uint" => $"UIntReturnCallback(lambda _self, result: _copy_uint({propertySource}, result))",
            "double" => $"DoubleReturnCallback(lambda _self, result: _copy_double({propertySource}, result))",
            "Symbol" => $"IntReturnCallback(lambda _self, result: _copy_int(int({propertySource}), result))",
            _ => $"IntReturnCallback(lambda _self, result: _copy_int(int({propertySource}), result))"
        };
    }

    private static string PythonPropertySource(MethodWithOwner method, string targetPrefix, string propertyName)
    {
        return ShortName(method.Owner.FullName) switch
        {
            "IEntryExtension" => $"{targetPrefix}.metadata.{propertyName}",
            "ISettingsExtension" when propertyName is "description_uri" or "token" or "placeholder" => $"{targetPrefix}.metadata.{propertyName}",
            "ISettingsExtension" when propertyName is "settings_type" => $"{targetPrefix}.settings_type",
            _ => $"{targetPrefix}.{propertyName}"
        };
    }

    private static string PythonCallbackType(MethodDefinition method, PidlMetadata metadata)
    {
        var parameters = method.Parameters.Select(parameter => PythonCallbackParameterType(method, parameter, metadata)).ToList();
        if (method.ReturnType is not "void")
            parameters.Add(PythonCallbackReturnType(method, metadata));

        return $"_abi.CALLBACK(_abi.HRESULT, _abi.VOIDP{(parameters.Count is 0 ? "" : ", " + string.Join(", ", parameters))})";
    }

    private static string PythonCallbackReturnType(MethodDefinition method, PidlMetadata metadata)
    {
        if (method.ReturnArrayCountName is not null)
            return "ctypes.POINTER(_abi.VOIDP)";

        return method.ReturnType switch
        {
            "bool" => $"ctypes.POINTER({PythonBoolAbiType(metadata)})",
            "int" or "Symbol" => "ctypes.POINTER(_abi.INT32)",
            "uint" => "ctypes.POINTER(_abi.UINT32)",
            "double" => "ctypes.POINTER(_abi.DOUBLE)",
            "string" or "string?" => "ctypes.POINTER(_abi.VOIDP)",
            "byte[]" or "byte[]?" or "string[]" => "ctypes.POINTER(_abi.VOIDP)",
            _ when method.ReturnType.EndsWith("Type", StringComparison.Ordinal) => "ctypes.POINTER(_abi.INT32)",
            _ => "ctypes.POINTER(_abi.INT32)"
        };
    }

    private static string PythonCallbackParameterType(MethodDefinition method, ParameterDefinition parameter, PidlMetadata metadata)
    {
        if (parameter.IsOut)
        {
            var pointerType = parameter.Type switch
            {
                "int" => "_abi.INT32",
                "long" => "_abi.INT64",
                "uint" => "_abi.UINT32",
                "double" => "_abi.DOUBLE",
                _ => "_abi.VOIDP"
            };
            return $"ctypes.POINTER({pointerType})";
        }

        if (parameter.ArrayCountName is not null)
            return "_abi.VOIDP";

        return parameter.Type switch
        {
            "bool" => PythonBoolAbiType(metadata),
            "int" => "_abi.INT32",
            "uint" => "_abi.UINT32",
            "long" => "_abi.INT64",
            "double" => "_abi.DOUBLE",
            "string" or "string?" => "_abi.VOIDP",
            "IStream" or "ITaskCompletionSource" or "IProgressNotifier" => "_abi.VOIDP",
            _ when parameter.Type.EndsWith("[]", StringComparison.Ordinal) => "_abi.VOIDP",
            _ when IsInterfaceType(parameter.Type) => "_abi.VOIDP",
            _ => "_abi.INT32"
        };
    }

    private static IReadOnlyList<PythonField> PythonFieldsForMethods(IReadOnlyList<MethodWithOwner> methods)
    {
        var fields = new List<PythonField>();
        foreach (var method in methods)
        {
            if (method.Method.PropertyName is not null)
                fields.Add(new PythonField(ToSnakeCase(method.Method.PropertyName), PythonAnnotation(method.Method), null));
        }

        return fields
            .GroupBy(static field => field.Name, StringComparer.Ordinal)
            .Select(static group => group.First())
            .ToList();
    }

    private static IReadOnlyList<PythonField> PythonConstructorFields(PythonModelContext context, InterfaceDefinition definition)
    {
        return PythonFieldsForMethods(context.FlattenMethods(definition)
            .Where(static method => method.Method.PropertyName is not null)
            .ToList());
    }

    private static string PythonConstructorParameters(IReadOnlyList<PythonField> fields)
    {
        if (fields.Count is 0)
            return "";

        return ", " + string.Join(", ", fields
            .Where(static field => field.Name is not "value")
            .Select(static field => $"{field.Name}: {field.Annotation}{field.DefaultValue ?? ""}"));
    }

    private static string PythonAnnotation(string pidlType)
    {
        return pidlType switch
        {
            "bool" => "bool",
            "int" or "uint" or "long" => "int",
            "double" => "float",
            "string" or "string?" => "str",
            "byte[]?" or "byte[]" => "bytes",
            "string[]" => "Sequence[str]",
            "Symbol" => "Symbol",
            "IStream" => "_abi.Stream",
            "IProgressNotifier" => "_abi.ProgressNotifier",
            "ITaskCompletionSource" => "_abi.TaskCompletionSource",
            _ when pidlType.EndsWith("Type", StringComparison.Ordinal) => $"_abi.{pidlType}",
            _ => "int"
        };
    }

    private static string PythonAnnotation(MethodDefinition method)
    {
        if (method.ReturnDictionary is { } dictionary)
            return PythonDictionaryAnnotation(dictionary);

        if (method.ReturnDateTimeOffset is not null)
            return "tuple[int, int]";

        return PythonAnnotation(method.ReturnType);
    }

    private static void AppendPythonValueChangedMethods(StringBuilder builder, MethodWithOwner method, PidlMetadata metadata)
    {
        if (method.Method.Parameters.Count is 1)
        {
            var parameter = method.Method.Parameters[0];
            var annotation = PythonAnnotation(parameter.Type);
            var converter = parameter.Type switch
            {
                "bool" => PythonBoolToPython(metadata, parameter.Name),
                "string" => $"_abi.read_utf16({parameter.Name})",
                _ => parameter.Name
            };
            _ = builder.AppendLine(
                $"""

                     def on_value_changed(self, value: {annotation}) -> None:
                         self.value = value

                     def _on_value_changed(self, _self: int, {parameter.Name}: {PythonParameterAnnotation(parameter, metadata)}) -> int:
                         self.on_value_changed({converter})
                         return _abi.S_OK

                 """);
        }
        else if (method.Method.Parameters.FirstOrDefault(static parameter => parameter.ArrayCountName is not null) is { } array)
        {
            _ = builder.AppendLine(
                $"""

                     def on_value_changed(self, value: list[str]) -> None:
                         self.value = value

                     def _on_value_changed(self, _self: int, {array.Name}: int, {array.ArrayCountName}: int) -> int:
                         self.on_value_changed(_abi.read_utf16_array({array.Name}, {array.ArrayCountName}))
                         return _abi.S_OK

                 """);
        }
    }

    private static void AppendPythonDateTimeOffsetMethods(
        StringBuilder builder,
        MethodDefinition? getter,
        MethodDefinition? changed,
        PidlMetadata metadata)
    {
        if (changed?.DateTimeOffsetParameters is [{ } dateTimeOffset])
        {
            _ = builder.AppendLine(
                $"""

                     def on_value_changed(self, {ToSnakeCase(dateTimeOffset.TicksName)}: int, {ToSnakeCase(dateTimeOffset.OffsetName)}: int) -> None:
                         self.value = ({ToSnakeCase(dateTimeOffset.TicksName)}, {ToSnakeCase(dateTimeOffset.OffsetName)})

                 """);
        }

        if (getter?.ReturnDateTimeOffset is { } returnDateTimeOffset)
        {
            var parameters = string.Join(", ", getter.Parameters.Select(parameter => $"{parameter.Name}: {PythonParameterAnnotation(parameter, metadata)}"));
            _ = builder.AppendLine(
                $"""

                     def {PythonPrivateMethodName(getter.Name)}(self, _self: int, {parameters}) -> int:
                         if not {returnDateTimeOffset.TicksName} or not {returnDateTimeOffset.OffsetName}:
                             return _abi.E_POINTER
                         {returnDateTimeOffset.TicksName}[0], {returnDateTimeOffset.OffsetName}[0] = self.default_value
                         return _abi.S_OK

                 """);
        }

        if (changed?.DateTimeOffsetParameters is [{ } value])
        {
            var parameters = string.Join(", ", changed.Parameters.Select(parameter => $"{parameter.Name}: {PythonParameterAnnotation(parameter, metadata)}"));
            _ = builder.AppendLine(
                $"""
                     def {PythonPrivateMethodName(changed.Name)}(self, _self: int, {parameters}) -> int:
                         self.on_value_changed({value.TicksName}, {value.OffsetName})
                         return _abi.S_OK

                 """);
        }
    }

    private static void AppendPythonExtensionMethod(
        StringBuilder builder,
        MethodWithOwner method,
        PidlMetadata metadata,
        MethodWithOwner? asyncResultGetter)
    {
        var methodName = ToSnakeCase(method.Method.Name);
        var skipTask = IsPythonTaskMethod(method.Method);
        var publicParameters = PythonPublicParameters(method.Method, skipTask).ToList();
        _ = builder.AppendLine(
            $"""

                def {methodName}(self{(publicParameters.Count is 0 ? "" : ", " + string.Join(", ", publicParameters))}) -> {PythonReturnAnnotation(method.Method, asyncResultGetter?.Method)}:
            {PythonDefaultBody(method, asyncResultGetter?.Method)}

            """);
        _ = builder.AppendLine(PythonPrivateMethod(method, metadata, asyncResultGetter?.Method));
    }

    private static string PythonDefaultBody(MethodWithOwner method, MethodDefinition? asyncResultGetter)
    {
        if (method.Method.Name is "TransformAsync" && method.Method.Parameters.Any(static parameter => parameter.IsBuiltInStream))
            return "        original_stream.copy_to(destination_stream)";
        if (asyncResultGetter is not null)
            return PythonDefaultReturnBody(asyncResultGetter);
        if (method.Method.ReturnType is not "void")
            return PythonDefaultReturnBody(method.Method);
        return "        pass";
    }

    private static string PythonDefaultReturnBody(MethodDefinition method)
    {
        if (method.ReturnDictionary is not null)
            return "        return {}";

        if (method.ReturnDateTimeOffset is not null)
            return "        return (0, 0)";

        if (method.ReturnArrayCountName is not null)
        {
            return method.ReturnType switch
            {
                "byte[]" or "byte[]?" => "        return b\"\"",
                _ => "        return []"
            };
        }

        return method.ReturnType switch
        {
            "string" or "string?" => "        return \"\"",
            "bool" => "        return False",
            "IStream" => "        return _abi.Stream(None)",
            _ => "        return 0"
        };
    }

    private static string PythonPrivateMethod(
        MethodWithOwner method,
        PidlMetadata metadata,
        MethodDefinition? asyncResultGetter)
    {
        var privateName = PythonPrivateMethodName(method.Method.Name);
        var parameters = method.Method.Parameters.Select(parameter => $"{parameter.Name}: {PythonParameterAnnotation(parameter, metadata)}").ToList();
        if (method.Method.ReturnType is not "void")
            parameters.Add($"result: {PythonCallbackReturnType(method.Method, metadata)}");
        var builder = new StringBuilder();
        _ = builder.AppendLine($"    def {privateName}(self, _self: int{(parameters.Count is 0 ? "" : ", " + string.Join(", ", parameters))}) -> int:");
        if (method.Method.Name is "OnExtensionLoaded")
            _ = builder.AppendLine("        self.loaded = True");
        else if (method.Method.Name is "OnExtensionUnloaded")
            _ = builder.AppendLine("        self.loaded = False");
        var callArguments = PythonCallArguments(method.Method, metadata, IsPythonTaskMethod(method.Method)).ToList();
        var call = $"{ToSnakeCase(method.Method.Name)}({string.Join(", ", callArguments)})";
        if (asyncResultGetter is not null)
        {
            _ = builder.AppendLine(
                $"""
                        value = self.{call}
                        self.{PythonAsyncResultFieldName(asyncResultGetter)} = value
                        _complete_task(task)
                        return _abi.S_OK
                """);
            return builder.ToString().TrimEnd();
        }

        if (method.Method.ReturnType is "void")
        {
            _ = builder.AppendLine($"        self.{call}");
            if (method.Method.Parameters.Any(static parameter => parameter.Name is "task"))
            {
                _ = builder.AppendLine("        _complete_task(task)");
            }

            _ = builder.AppendLine("        return _abi.S_OK");
        }
        else
        {
            _ = builder.AppendLine(
                $"""
                        value = self.{call}
                        return {PythonCopyReturnValue(method.Method.ReturnType, "value", "result", metadata)}
                """);
        }

        return builder.ToString().TrimEnd();
    }

    private static void AppendPythonAsyncResultGetter(StringBuilder builder, MethodWithOwner method, PidlMetadata metadata)
    {
        var privateName = PythonPrivateMethodName(method.Method.Name);
        var parameters = method.Method.Parameters.Select(parameter => $"{parameter.Name}: {PythonParameterAnnotation(parameter, metadata)}").ToList();
        if (method.Method.ReturnType is not "void")
            parameters.Add($"result: {PythonCallbackReturnType(method.Method, metadata)}");
        var fieldName = PythonAsyncResultFieldName(method.Method);

        _ = builder.AppendLine(
            $"""

                def {privateName}(self, _self: int{(parameters.Count is 0 ? "" : ", " + string.Join(", ", parameters))}) -> int:
                    value = getattr(self, "{fieldName}", {PythonDefaultValue(method.Method)})
            """);
        foreach (var line in PythonCopyAsyncResultLines(method.Method, "value", metadata))
            _ = builder.AppendLine($"        {line}");
    }

    private static string PythonBoolReturnCallback(PidlMetadata metadata, string value)
    {
        return metadata.BoolMarshalling switch
        {
            BoolMarshallingMode.BOOL => $"IntReturnCallback(lambda _self, result: _copy_int({PythonBoolToAbi(metadata, value)}, result))",
            _ => throw new ArgumentOutOfRangeException(nameof(metadata))
        };
    }

    private static string PythonBoolAbiType(PidlMetadata metadata)
    {
        return metadata.BoolMarshalling switch
        {
            BoolMarshallingMode.BOOL => "_abi.INT32",
            _ => throw new ArgumentOutOfRangeException(nameof(metadata))
        };
    }

    private static string PythonBoolToAbi(PidlMetadata metadata, string value)
    {
        return metadata.BoolMarshalling switch
        {
            BoolMarshallingMode.BOOL => $"(1 if {value} else 0)",
            _ => throw new ArgumentOutOfRangeException(nameof(metadata))
        };
    }

    private static string PythonBoolToPython(PidlMetadata metadata, string value)
    {
        return metadata.BoolMarshalling switch
        {
            BoolMarshallingMode.BOOL => $"({value} != 0)",
            _ => throw new ArgumentOutOfRangeException(nameof(metadata))
        };
    }

    private static string PythonParameterAnnotation(ParameterDefinition parameter, PidlMetadata metadata)
    {
        if (parameter.IsOut)
        {
            return parameter.Type switch
            {
                "int" => "ctypes.POINTER(_abi.INT32)",
                "long" => "ctypes.POINTER(_abi.INT64)",
                "uint" => "ctypes.POINTER(_abi.UINT32)",
                "double" => "ctypes.POINTER(_abi.DOUBLE)",
                _ => "ctypes.POINTER(_abi.VOIDP)"
            };
        }

        return parameter.Type switch
        {
            "bool" => PythonBoolAbiType(metadata),
            _ => "int"
        };
    }

    private static string PythonCopyReturnValue(string returnType, string value, string result, PidlMetadata metadata)
    {
        return returnType switch
        {
            "string" or "string?" => $"_abi.copy_utf16({value}, {result})",
            "bool" => $"_copy_int({PythonBoolToAbi(metadata, value)}, {result})",
            "int" => $"_copy_int({value}, {result})",
            "uint" => $"_copy_uint({value}, {result})",
            "double" => $"_copy_double({value}, {result})",
            "Symbol" => $"_copy_int(int({value}), {result})",
            _ when returnType.EndsWith("Type", StringComparison.Ordinal) => $"_copy_int(int({value}), {result})",
            _ => $"_copy_int(int({value}), {result})"
        };
    }

    private static IEnumerable<string> PythonCopyAsyncResultLines(MethodDefinition method, string value, PidlMetadata metadata)
    {
        if (method.ReturnDictionary is { } dictionary)
        {
            yield return $"keys = list({value}.keys())";
            yield return $"items = list({value}.values())";
            yield return $"hr = {PythonCopyDictionaryElement(dictionary.KeyType, "keys", dictionary.CountName, dictionary.KeysName)}";
            yield return "if hr != _abi.S_OK:";
            yield return "    return hr";
            yield return $"{dictionary.CountName}[0] = len(value)";
            yield return $"return {PythonCopyDictionaryElement(dictionary.ValueType, "items", "", dictionary.ValuesName)}";
            yield break;
        }

        if (method.ReturnDateTimeOffset is { } dateTimeOffset)
        {
            yield return $"if not {dateTimeOffset.TicksName} or not {dateTimeOffset.OffsetName}:";
            yield return "    return _abi.E_POINTER";
            yield return $"{dateTimeOffset.TicksName}[0], {dateTimeOffset.OffsetName}[0] = {value}";
            yield return "return _abi.S_OK";
            yield break;
        }

        if (method.ReturnArrayCountName is { } returnCountName)
        {
            yield return $"return {PythonCopyArrayReturnValue(method.ReturnType, value, returnCountName, "result")}";
            yield break;
        }

        if (method is { ReturnIsBuiltInStream: true, ReturnType: "IStream" })
        {
            yield return "if not result:";
            yield return "    return _abi.E_POINTER";
            yield return $"result[0] = {value}.native";
            yield return "return _abi.S_OK";
            yield break;
        }

        yield return $"return {PythonCopyReturnValue(method.ReturnType, value, "result", metadata)}";
    }

    private static string PythonCopyArrayReturnValue(string returnType, string value, string count, string result)
    {
        return ElementType(returnType) switch
        {
            "string" => $"_abi.copy_utf16_array({value}, {count}, {result})",
            "byte" => $"_abi.copy_bytes({value} or b\"\", {count}, {result})",
            "int" => $"_abi.copy_int32_array({value}, {result})",
            "IStream" => $"_abi.copy_pointer_array((stream.native for stream in {value}), {count}, {result})",
            "IExtension" => $"_abi.copy_pointer_array((extension.export() for extension in {value}), {count}, {result})",
            _ => $"_abi.copy_pointer_array({value}, {count}, {result})"
        };
    }

    private static string PythonDefaultValue(MethodDefinition method)
    {
        if (method.ReturnDictionary is not null)
            return "{}";

        if (method.ReturnDateTimeOffset is not null)
            return "(0, 0)";

        if (method.ReturnArrayCountName is not null)
        {
            return method.ReturnType switch
            {
                "byte[]" or "byte[]?" => "b\"\"",
                _ => "[]"
            };
        }

        return method.ReturnType switch
        {
            "string" or "string?" => "\"\"",
            "bool" => "False",
            "IStream" => "_abi.Stream(None)",
            _ => "0"
        };
    }

    private static string PythonReadArgument(MethodDefinition method, ParameterDefinition parameter, PidlMetadata metadata)
    {
        if (parameter.ArrayCountName is { } countName)
        {
            var elementType = ElementType(parameter.Type);
            return elementType switch
            {
            "string" => $"_abi.read_utf16_array({parameter.Name}, {countName})",
            "IStream" => $"[_abi.Stream(pointer) for pointer in _abi.read_pointer_array({parameter.Name}, {countName})]",
                "int" => $"_abi.read_int32_array({parameter.Name}, {countName})",
                _ => $"_abi.read_pointer_array({parameter.Name}, {countName})"
            };
        }

        return parameter.Type switch
        {
            "string" or "string?" => $"_abi.read_utf16({parameter.Name})",
            "bool" => PythonBoolToPython(metadata, parameter.Name),
            "IStream" => $"_abi.Stream({parameter.Name})",
            "IProgressNotifier" => $"_abi.ProgressNotifier({parameter.Name})",
            "ITaskCompletionSource" => $"_abi.TaskCompletionSource({parameter.Name})",
            _ when parameter.Type.EndsWith("Type", StringComparison.Ordinal) => $"_abi.{parameter.Type}({parameter.Name})",
            _ => parameter.Name
        };
    }

    private static void AppendPythonPropertyDefault(StringBuilder builder, MethodWithOwner method)
    {
        var property = ToSnakeCase(method.Method.PropertyName!);
        if (method.Method.ReturnType is "string")
            _ = builder.AppendLine($"    {property} = \"\"");
        else if (method.Method.ReturnType is "Symbol")
            _ = builder.AppendLine($"    {property} = Symbol.Settings");
    }

    private static string PythonSdkParameterAnnotation(MethodDefinition method, ParameterDefinition parameter)
    {
        if (parameter.ArrayCountName is not null)
            return $"list[{PythonAnnotation(ElementType(parameter.Type))}]";

        return parameter.Type switch
        {
            "IStream" => "_abi.Stream",
            "IProgressNotifier" => "_abi.ProgressNotifier",
            _ => PythonAnnotation(parameter.Type)
        };
    }

    private static string PythonReturnAnnotation(MethodDefinition method)
    {
        return method.ReturnType is "void" ? "None" : PythonAnnotation(method.ReturnType);
    }

    private static string PythonReturnAnnotation(MethodDefinition method, MethodDefinition? asyncResultGetter)
    {
        if (asyncResultGetter is not null)
            return PythonAnnotation(asyncResultGetter);

        return PythonReturnAnnotation(method);
    }

    private static bool IsPythonTaskMethod(MethodDefinition method)
    {
        return method.IsAsync;
    }

    private static MethodWithOwner? FindAsyncResultGetter(IReadOnlyList<MethodWithOwner> methods, MethodDefinition taskMethod)
    {
        return methods
            .FirstOrDefault(method => ReferenceEquals(method.Method.AsyncSourceMethod, taskMethod));
    }

    private static void AppendPythonReturnDictionaryMethod(StringBuilder builder, MethodWithOwner method, PidlMetadata metadata)
    {
        var dictionary = method.Method.ReturnDictionary!;
        var propertyName = ToSnakeCase(method.Method.PropertyName ?? method.Method.Name);
        var parameters = string.Join(", ", method.Method.Parameters.Select(parameter => $"{parameter.Name}: {PythonParameterAnnotation(parameter, metadata)}"));
        _ = builder.AppendLine(
            $"""

                 def {PythonPrivateMethodName(method.Method.Name)}(self, _self: int, {parameters}) -> int:
                     values = self.{propertyName}
                     keys = list(values.keys())
                     items = list(values.values())
                     hr = {PythonCopyDictionaryElement(dictionary.KeyType, "keys", dictionary.CountName, dictionary.KeysName)}
                     if hr != _abi.S_OK:
                         return hr
                     {dictionary.CountName}[0] = len(values)
                     return {PythonCopyDictionaryElement(dictionary.ValueType, "items", "", dictionary.ValuesName)}

             """);
    }

    private static IEnumerable<string> PythonPublicParameters(MethodDefinition method, bool skipTask)
    {
        var start = skipTask ? 1 : 0;
        for (var i = start; i < method.Parameters.Count; ++i)
        {
            if (TryMatchDictionaryExpansion(method, i, out var dictionary))
            {
                yield return $"{PythonIdentifier(ToSnakeCase(dictionary.Name))}: {PythonDictionaryAnnotation(dictionary)}";
                ++i;
                continue;
            }

            var parameter = method.Parameters[i];
            if (parameter.IsGeneratedArrayCount)
                continue;

            yield return $"{PythonIdentifier(ToSnakeCase(parameter.Name))}: {PythonSdkParameterAnnotation(method, parameter)}";
        }
    }

    private static IEnumerable<string> PythonCallArguments(MethodDefinition method, PidlMetadata metadata, bool skipTask)
    {
        var start = skipTask ? 1 : 0;
        for (var i = start; i < method.Parameters.Count; ++i)
        {
            if (TryMatchDictionaryExpansion(method, i, out var dictionary))
            {
                yield return PythonReadDictionaryArgument(dictionary);
                ++i;
                continue;
            }

            var parameter = method.Parameters[i];
            if (parameter.IsGeneratedArrayCount)
                continue;

            yield return PythonReadArgument(method, parameter, metadata);
        }
    }

    private static bool TryMatchDictionaryExpansion(MethodDefinition method, int index, out DictionaryExpansion dictionary)
    {
        dictionary = null!;
        if (index + 1 >= method.Parameters.Count)
            return false;

        var keys = method.Parameters[index];
        var values = method.Parameters[index + 1];
        var match = method.DictionaryParameters.FirstOrDefault(expansion =>
            expansion.KeysName == keys.Name &&
            expansion.ValuesName == values.Name);
        if (match is null)
            return false;

        dictionary = match;
        return true;
    }

    private static string PythonReadDictionaryArgument(DictionaryExpansion dictionary)
    {
        var keys = PythonReadDictionaryElement(dictionary.KeyType, dictionary.KeysName, dictionary.CountName);
        var values = PythonReadDictionaryElement(dictionary.ValueType, dictionary.ValuesName, dictionary.CountName);
        return $"dict(zip({keys}, {values}))";
    }

    private static string PythonReadDictionaryElement(string type, string name, string countName)
    {
        return type switch
        {
            "string" => $"_abi.read_utf16_array({name}, {countName})",
            "IStream" => $"[_abi.Stream(pointer) for pointer in _abi.read_pointer_array({name}, {countName})]",
            "int" => $"_abi.read_int32_array({name}, {countName})",
            _ => $"_abi.read_pointer_array({name}, {countName})"
        };
    }

    private static string PythonDictionaryAnnotation(DictionaryExpansion dictionary)
    {
        return $"dict[{PythonDictionaryElementAnnotation(dictionary.KeyType)}, {PythonDictionaryElementAnnotation(dictionary.ValueType)}]";
    }

    private static string PythonDictionaryElementAnnotation(string type)
    {
        return type is "IStream" ? "_abi.Stream" : PythonAnnotation(type);
    }

    private static string PythonCopyDictionaryElement(string type, string values, string count, string result)
    {
        return type switch
        {
            "string" => $"_abi.copy_utf16_array({values}, {count}, {result})",
            "int" => $"_abi.copy_int32_array({values}, {result})",
            _ => $"_abi.copy_pointer_array((value.native for value in {values}), {count}, {result})"
        };
    }

    private static string PythonPrivateMethodName(string name)
    {
        return "_" + ToSnakeCase(name);
    }

    private static string PythonAsyncResultFieldName(MethodDefinition resultGetter)
    {
        return "_" + ToSnakeCase(GetDefaultPropertyName(resultGetter.Name));
    }

    private static string GetDefaultPropertyName(string methodName)
    {
        if (methodName.Length > 3 &&
            (methodName.StartsWith("Get", StringComparison.Ordinal) || methodName.StartsWith("Set", StringComparison.Ordinal)))
            return methodName[3..];

        return methodName;
    }

    private static string PythonIidList(IEnumerable<InterfaceDefinition> interfaces)
    {
        return string.Join(", ", new[] { "_abi.IID_IUNKNOWN" }.Concat(interfaces.Select(static value => "_abi.IID_" + ConstantName(value))));
    }

    private static string PythonSdkClassName(InterfaceDefinition definition)
    {
        var sdkName = definition.SdkName ?? ShortName(definition.FullName);
        return sdkName.EndsWith("Base", StringComparison.Ordinal) ? sdkName[..^"Base".Length] : sdkName;
    }

    private static IReadOnlyList<InterfaceDefinition> OrderPythonSdkDefinitions(PythonModelContext context, PidlModel model)
    {
        var definitions = model.Interfaces
            .Where(static definition => definition.SdkName is not null)
            .ToList();
        var pending = definitions.ToHashSet();
        var ordered = new List<InterfaceDefinition>();

        while (pending.Count > 0)
        {
            var added = false;
            foreach (var definition in pending.ToList())
            {
                var baseInterface = context.ResolveSdkBaseInterface(definition);
                if (baseInterface is not null && pending.Contains(baseInterface))
                    continue;

                ordered.Add(definition);
                _ = pending.Remove(definition);
                added = true;
            }

            if (!added)
                throw new InvalidOperationException("A cycle was found in Python SDK base definitions.");
        }

        return ordered;
    }

    private static bool IsConcreteSettingsInterface(PythonModelContext context, InterfaceDefinition definition, out string settingsType)
    {
        settingsType = "";
        if (ShortName(definition.FullName) is "ISettingsExtension" ||
            !context.FlattenInterfaces(definition).Any(static value => ShortName(value.FullName) is "ISettingsExtension"))
            return false;

        var shortName = ShortName(definition.FullName);
        if (!shortName.StartsWith('I') ||
            !shortName.EndsWith("SettingsExtension", StringComparison.Ordinal))
            return false;

        settingsType = shortName[1..^"SettingsExtension".Length];
        return settingsType.Length > 0;
    }

    private static string ElementType(string type)
    {
        if (type.EndsWith("[]?", StringComparison.Ordinal))
            return type[..^3];

        return type.EndsWith("[]", StringComparison.Ordinal) ? type[..^2] : type;
    }

    private static bool IsInterfaceType(string type)
    {
        return type.Length > 1 &&
               type[0] is 'I' &&
               char.IsUpper(type[1]) &&
               !type.EndsWith("[]", StringComparison.Ordinal);
    }

    private static bool IsMetadataBackedProperty(string ownerShortName, string fieldName)
    {
        return ownerShortName switch
        {
            "IEntryExtension" => fieldName is "icon" or "label" or "description",
            "ISettingsExtension" => fieldName is "description_uri" or "token" or "placeholder" or "settings_type",
            _ => false
        };
    }

    private sealed record PythonField(string Name, string Annotation, string? DefaultValue);

    private static void AppendSdkPresetManifest(StringBuilder builder, PidlModel model)
    {
        var presets = model.Interfaces
            .Where(static definition => definition.SdkName is not null)
            .Select(static definition => definition.SdkName!)
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .ToList();

        _ = builder.AppendLine("# PIDL SDK presets available in this package:");
        foreach (var preset in presets)
            _ = builder.AppendLine($"# - {preset}");
    }

    private static string ConstantName(InterfaceDefinition definition)
    {
        var name = ShortName(definition.FullName);
        if (name.StartsWith('I') && name.Length > 1 && char.IsUpper(name[1]))
            name = name[1..];

        return ToSnakeCase(name).ToUpperInvariant();
    }

    private static string PythonIdentifier(string value)
    {
        return _PythonKeywords.Contains(value) ? value + "_" : value;
    }

    private static string ToSnakeCase(string value)
    {
        var builder = new StringBuilder();
        for (var i = 0; i < value.Length; i++)
        {
            var current = value[i];
            if (char.IsUpper(current) && i > 0)
                _ = builder.Append('_');
            _ = builder.Append(char.ToLowerInvariant(current));
        }

        return builder.ToString();
    }

    private static string ShortName(string fullName)
    {
        var separator = fullName.LastIndexOf('.');
        return separator < 0 ? fullName : fullName[(separator + 1)..];
    }

    private sealed class PythonModelContext
    {
        private readonly Dictionary<string, InterfaceDefinition> _interfaces;

        public PythonModelContext(PidlModel model)
        {
            _interfaces = model.Interfaces
                .SelectMany(static definition => new[]
                {
                    new KeyValuePair<string, InterfaceDefinition>(definition.FullName, definition),
                    new KeyValuePair<string, InterfaceDefinition>(ShortName(definition.FullName), definition)
                })
                .GroupBy(static pair => pair.Key, StringComparer.Ordinal)
                .ToDictionary(static group => group.Key, static group => group.First().Value, StringComparer.Ordinal);

            InterfacesWithGuid = model.Interfaces.Where(static definition => definition.Guid is not null).ToList();
        }

        public IReadOnlyList<InterfaceDefinition> InterfacesWithGuid { get; }

        public InterfaceDefinition RequireInterface(string name)
        {
            if (_interfaces.TryGetValue(name, out var definition))
                return definition;

            throw new InvalidOperationException($"Interface '{name}' was not found in PIDL.");
        }

        public InterfaceDefinition? ResolveSdkBaseInterface(InterfaceDefinition definition)
        {
            if (definition.Inherits is null)
                return null;

            var current = RequireInterface(definition.Inherits);
            while (true)
            {
                if (current.SdkName is not null)
                    return current;

                if (current.Inherits is null)
                    return null;

                current = RequireInterface(current.Inherits);
            }
        }

        public IReadOnlyList<InterfaceDefinition> FlattenInterfaces(InterfaceDefinition definition)
        {
            var result = new List<InterfaceDefinition>();
            AppendInterfaceChain(definition, result);
            return result;
        }

        public IReadOnlyList<MethodWithOwner> FlattenMethods(InterfaceDefinition definition)
        {
            return FlattenInterfaces(definition)
                .SelectMany(static owner => owner.Methods.Select(method => new MethodWithOwner(owner, method)))
                .ToList();
        }

        private void AppendInterfaceChain(InterfaceDefinition definition, List<InterfaceDefinition> result)
        {
            if (definition.Inherits is not null)
                AppendInterfaceChain(RequireInterface(definition.Inherits), result);

            result.Add(definition);
        }
    }

    private sealed record MethodWithOwner(InterfaceDefinition Owner, MethodDefinition Method);
}
