using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Pixeval.Extensions.Generator.Models;
using PidlType = Pixeval.Extensions.Generator.TypeNames.Pidl;
using PythonType = Pixeval.Extensions.Generator.TypeNames.Python;

namespace Pixeval.Extensions.Generator;

internal static class PythonEmitter
{
    private static readonly HashSet<string> _PythonKeywords = new(StringComparer.Ordinal)
    {
        "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
        "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
        "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
        "with", "yield", "match", "case"
    };

    public static string EmitCommon(PidlModel model)
    {
        var context = new PythonModelContext(model);
        var builder = new StringBuilder();
        _ = builder.AppendLine(
            """
            # <auto-generated />
            from __future__ import annotations

            from enum import IntEnum

            from ._runtime import *

            """);
        AppendEnums(builder, model);
        AppendIids(builder, context);
        AppendInterfaceMetadata(builder, context);
        return builder.ToString();
    }

    public static string EmitSdk(PidlModel model)
    {
        var context = new PythonModelContext(model);
        var builder = new StringBuilder();
        _ = builder.AppendLine(
            """
                # <auto-generated />
                from __future__ import annotations

                import ctypes
                from abc import abstractmethod
                from collections.abc import Sequence

                from . import abi as _abi
                from ._sdk_runtime import *
                from .symbols import Symbol

                SDK_VERSION = "{{SDK_VERSION}}"
                set_sdk_version(SDK_VERSION)

                """.Replace("{{SDK_VERSION}}", model.SdkVersion, StringComparison.Ordinal));
        AppendGeneratedSdkRuntime(builder, context, model);
        AppendSdkExports(builder, model);
        AppendSdkPresetManifest(builder, model);
        return builder.ToString();
    }

    private static void AppendEnums(StringBuilder builder, PidlModel model)
    {
        foreach (var definition in model.Enums)
        {
            _ = builder.AppendLine($"class {ShortName(definition.FullName)}(IntEnum):");
            var nextValue = 0;
            foreach (var value in definition.Values)
            {
                var actualValue = value.Value ?? nextValue.ToString();
                _ = builder.AppendLine($"    {PythonIdentifier(value.Name)} = {actualValue}");
                if (int.TryParse(actualValue, out var parsed))
                    nextValue = parsed + 1;
                else
                    ++nextValue;
            }

            _ = builder.AppendLine(
                """


                """);
        }
    }

    private static void AppendIids(StringBuilder builder, PythonModelContext context)
    {
        _ = builder.AppendLine("IID_IUNKNOWN = Guid.parse(\"00000000-0000-0000-C000-000000000046\")");
        foreach (var definition in context.InterfacesWithGuid)
            _ = builder.AppendLine($"IID_{ConstantName(definition)} = Guid.parse(\"{definition.Guid}\")");
        _ = builder.AppendLine(
            """


            """);
    }

    private static void AppendInterfaceMetadata(StringBuilder builder, PythonModelContext context)
    {
        _ = builder.AppendLine(
            "INTERFACE_IIDS = {");
        foreach (var definition in context.InterfacesWithGuid)
        {
            _ = builder.AppendLine($"    \"{ShortName(definition.FullName)}\": IID_{ConstantName(definition)},");
        }

        _ = builder.AppendLine(
            """
            }

            INTERFACE_CHAINS = {
            """);
        foreach (var definition in context.InterfacesWithGuid)
        {
            var chain = context.FlattenInterfaces(definition)
                .Where(static value => value.Guid is not null)
                .Select(static value => $"\"{ShortName(value.FullName)}\"");
            _ = builder.AppendLine($"    \"{ShortName(definition.FullName)}\": [{string.Join(", ", chain)}],");
        }

        _ = builder.AppendLine(
            """
            }

            INTERFACE_SLOTS = {
            """);
        foreach (var definition in context.InterfacesWithGuid)
        {
            _ = builder.AppendLine($"    \"{ShortName(definition.FullName)}\": {{");
            var slot = 3;
            foreach (var method in context.FlattenMethods(definition, includeOverrides: false))
            {
                _ = builder.AppendLine($"        \"{ShortName(method.Owner.FullName)}.{method.Method.Name}\": {slot++},");
            }

            _ = builder.AppendLine("    },");
        }
        _ = builder.AppendLine(
            """
            }


            """);
    }

    private static void AppendGeneratedSdkRuntime(StringBuilder builder, PythonModelContext context, PidlModel model)
    {
        foreach (var definition in OrderPythonSdkDefinitions(context, model))
            AppendPythonSdkClass(builder, context, model.Metadata, definition);

        foreach (var definition in model.Interfaces.Where(static definition => definition.SdkName is not null))
        {
            var alias = definition.SdkName!;
            var className = PythonSdkClassName(definition);
            if (alias != className)
                _ = builder.AppendLine($"{alias} = {className}");
        }
    }

    private static void AppendSdkExports(StringBuilder builder, PidlModel model)
    {
        var exports = new SortedSet<string>(StringComparer.Ordinal)
        {
            "SDK_VERSION",
            "ExtensionsHostBase",
            "EntryMetadata",
            "read_icon"
        };

        foreach (var definition in model.Interfaces.Where(static definition => definition.SdkName is not null))
        {
            _ = exports.Add(PythonSdkClassName(definition));
            _ = exports.Add(definition.SdkName!);
        }

        _ = builder.AppendLine("__all__ = [");
        foreach (var export in exports)
            _ = builder.AppendLine($"    \"{export}\",");
        _ = builder.AppendLine(
            """
            ]

            """);
    }

    private static void AppendPythonSdkClass(StringBuilder builder, PythonModelContext context, PidlMetadata metadata, InterfaceDefinition definition)
    {
        var className = PythonSdkClassName(definition);
        var baseInterface = context.ResolveSdkBaseInterface(definition);
        var baseClass = baseInterface is null ? PythonType.SdkComObject : PythonSdkClassName(baseInterface);
        var methodChain = context.FlattenMethods(definition);
        var inheritedInterfaces = baseInterface is null
            ? []
            : context.FlattenInterfaces(baseInterface).ToHashSet();
        var ownMethods = methodChain.Where(method => !inheritedInterfaces.Contains(method.Owner)).ToList();
        var concreteInterfaces = context.FlattenInterfaces(definition).Where(static value => value.Guid is not null).ToList();

        _ = builder.AppendLine($"class {className}({baseClass}):");
        AppendPythonAbstractInstantiationGuard(builder, className);
        AppendPythonConstructor(builder, metadata, ownMethods, concreteInterfaces);
        foreach (var method in ownMethods.Where(static method => method.Method is { PropertyAccessor: PropertyAccessorKind.None, IsAsyncResultGetter: false }))
            AppendPythonExtensionMethod(builder, method, metadata, FindAsyncResultGetter(ownMethods, method.Method));
        foreach (var method in ownMethods.Where(static method => method.Method is { IsAsyncResultGetter: true }))
            AppendPythonAsyncResultGetter(builder, method, metadata);
        AppendPythonProperties(builder, ownMethods);
        AppendPythonPropertyCallbackMethods(builder, ownMethods, metadata);
    }

    private static void AppendPythonAbstractInstantiationGuard(StringBuilder builder, string className)
    {
        _ = builder.AppendLine(
            $"""
                def __new__(cls, *args, **kwargs):
                    if cls is {className}:
                        raise TypeError("{className} is an abstract SDK base class")
                    return super().__new__(cls)

            """);
    }

    private static void AppendPythonConstructor(
        StringBuilder builder,
        PidlMetadata metadata,
        IReadOnlyList<MethodWithOwner> ownMethods,
        IReadOnlyList<InterfaceDefinition> concreteInterfaces)
    {
        _ = builder.AppendLine($"    def __init__(self, interfaces: {PythonType.AbiInterfaceSet} | {PythonType.None} = {PythonType.None}, extra_callbacks: {PythonType.SequenceOf(PythonType.CTypesCFuncPtr)} = ()) -> None:");
        if (ownMethods.Any(static method => method.Method.Name is "OnExtensionLoaded"))
            _ = builder.AppendLine("        self.loaded = False");
        AppendPythonCallbackList(builder, ownMethods, metadata, extendExtraCallbacks: true);
        _ = builder.AppendLine(
            $"""
                     super().__init__(
                         interfaces or _abi.InterfaceSet.of({PythonIidList(concreteInterfaces)}),
                         callbacks,
                     )
             """);
    }

    private static void AppendPythonCallbackList(
        StringBuilder builder,
        IReadOnlyList<MethodWithOwner> methods,
        PidlMetadata metadata,
        bool extendExtraCallbacks)
    {
        _ = builder.AppendLine(
            "        callbacks = [");
        foreach (var callback in methods.Where(static method => !method.Method.IsOverride).Select(method => PythonCallbackExpression(method, "self", metadata)))
        {
            _ = builder.AppendLine($"            {callback},");
        }

        _ = builder.AppendLine(
            "        ]");
        if (extendExtraCallbacks)
        {
            _ = builder.AppendLine(
                "        callbacks.extend(extra_callbacks)");
        }
    }

    private static string PythonCallbackExpression(MethodWithOwner method, string targetPrefix, PidlMetadata metadata)
    {
        if (method.Method.PropertyAccessor is not PropertyAccessorKind.None)
            return PythonPropertyCallback(method, targetPrefix, metadata);

        var callbackType = PythonCallbackType(method.Method, metadata);
        var target = PythonPrivateMethodName(method.Method.Name);
        return $"{callbackType}({targetPrefix}.{target})";
    }

    private static string PythonPropertyCallback(MethodWithOwner method, string targetPrefix, PidlMetadata metadata)
    {
        var propertyName = ToSnakeCase(method.Method.Property!.Name);
        var propertySource = $"{targetPrefix}.{propertyName}";
        if (method.Method.PropertyAccessor is PropertyAccessorKind.Setter)
            return $"{PythonCallbackType(method.Method, metadata)}({targetPrefix}.{PythonPrivateMethodName(method.Method.Name)})";

        if (method.Method.ReturnDictionary is not null)
            return $"{PythonCallbackType(method.Method, metadata)}({targetPrefix}.{PythonPrivateMethodName(method.Method.Name)})";

        if (method.Method.ReturnDateTimeOffset is not null)
            return $"_abi.CALLBACK({PythonType.AbiHResult}, {PythonType.AbiVoidPointer}, {PythonType.PointerTo(PythonType.AbiInt64)}, {PythonType.PointerTo(PythonType.AbiInt32)})({targetPrefix}.{PythonPrivateMethodName(method.Method.Name)})";

        if (method.Method.ReturnArrayCountName is not null)
            return $"ArrayReturnCallback(lambda _self, returnCount, result: {PythonCopyArrayReturnValue(method.Method.ReturnType, propertySource, "returnCount", "result")})";

        return method.Method.ReturnType switch
        {
            PidlType.String or PidlType.NullableString => $"StringReturnCallback(lambda _self, result: _abi.copy_utf16({propertySource}, result))",
            PidlType.Bool => PythonBoolReturnCallback(metadata, propertySource),
            PidlType.Int => $"IntReturnCallback(lambda _self, result: _copy_int({propertySource}, result))",
            PidlType.UInt => $"UIntReturnCallback(lambda _self, result: _copy_uint({propertySource}, result))",
            PidlType.Double => $"DoubleReturnCallback(lambda _self, result: _copy_double({propertySource}, result))",
            PidlType.Symbol => $"IntReturnCallback(lambda _self, result: _copy_int(int({propertySource}), result))",
            _ => $"IntReturnCallback(lambda _self, result: _copy_int(int({propertySource}), result))"
        };
    }

    private static string PythonCallbackType(MethodDefinition method, PidlMetadata metadata)
    {
        var parameters = method.Parameters.Select(parameter => PythonCallbackParameterType(method, parameter, metadata)).ToList();
        if (method.ReturnType is not PidlType.Void)
            parameters.Add(PythonCallbackReturnType(method, metadata));

        return $"_abi.CALLBACK({PythonType.AbiHResult}, {PythonType.AbiVoidPointer}{(parameters.Count is 0 ? "" : ", " + string.Join(", ", parameters))})";
    }

    private static string PythonCallbackReturnType(MethodDefinition method, PidlMetadata metadata)
    {
        if (method.ReturnArrayCountName is not null)
            return Pointer(PythonType.AbiVoidPointer);

        return method.ReturnType switch
        {
            PidlType.Bool => Pointer(PythonBoolAbiType(metadata)),
            PidlType.Int or PidlType.Symbol => Pointer(PythonType.AbiInt32),
            PidlType.UInt => Pointer(PythonType.AbiUInt32),
            PidlType.Double => Pointer(PythonType.AbiDouble),
            PidlType.String or PidlType.NullableString => Pointer(PythonType.AbiVoidPointer),
            PidlType.ByteArray or PidlType.NullableByteArray or PidlType.StringArray => Pointer(PythonType.AbiVoidPointer),
            _ when method.ReturnType.EndsWith(PidlType.EnumTypeSuffix, StringComparison.Ordinal) => Pointer(PythonType.AbiInt32),
            _ => Pointer(PythonType.AbiInt32)
        };
    }

    private static string Pointer(string pythonType)
    {
        return PythonType.PointerTo(pythonType);
    }

    private static string PythonCallbackParameterType(MethodDefinition method, ParameterDefinition parameter, PidlMetadata metadata)
    {
        if (parameter.IsOut)
        {
            var pointerType = parameter.Type switch
            {
                PidlType.Int => PythonType.AbiInt32,
                PidlType.Long => PythonType.AbiInt64,
                PidlType.UInt => PythonType.AbiUInt32,
                PidlType.Double => PythonType.AbiDouble,
                _ => PythonType.AbiVoidPointer
            };
            return Pointer(pointerType);
        }

        if (parameter.ArrayCountName is not null)
            return PythonType.AbiVoidPointer;

        return parameter.Type switch
        {
            PidlType.Bool => PythonBoolAbiType(metadata),
            PidlType.Int => PythonType.AbiInt32,
            PidlType.UInt => PythonType.AbiUInt32,
            PidlType.Long => PythonType.AbiInt64,
            PidlType.Double => PythonType.AbiDouble,
            PidlType.String or PidlType.NullableString => PythonType.AbiVoidPointer,
            PidlType.IStream or PidlType.ITaskCompletionSource or PidlType.IProgressNotifier => PythonType.AbiVoidPointer,
            _ when parameter.Type.EndsWith(PidlType.ArraySuffix, StringComparison.Ordinal) => PythonType.AbiVoidPointer,
            _ when IsInterfaceType(parameter.Type) => PythonType.AbiVoidPointer,
            _ => PythonType.AbiInt32
        };
    }

    private static IReadOnlyList<PythonProperty> BuildPythonProperties(IReadOnlyList<MethodWithOwner> methods)
    {
        var properties = new Dictionary<string, PythonProperty>(StringComparer.Ordinal);
        foreach (var method in methods.Where(static method => method.Method.PropertyAccessor is not PropertyAccessorKind.None))
        {
            var name = method.Method.Property!.Name;
            if (!properties.TryGetValue(name, out var property))
            {
                property = new PythonProperty(name);
                properties.Add(name, property);
            }

            switch (method.Method.PropertyAccessor)
            {
                case PropertyAccessorKind.Getter:
                    if (property.Getter is not null)
                        throw new InvalidOperationException($"Property '{name}' declares more than one getter.");
                    property.Getter = method;
                    break;
                case PropertyAccessorKind.Setter:
                    if (property.Setter is not null)
                        throw new InvalidOperationException($"Property '{name}' declares more than one setter.");
                    property.Setter = method;
                    break;
            }
        }

        return properties.Values.ToList();
    }

    private static void AppendPythonProperties(StringBuilder builder, IReadOnlyList<MethodWithOwner> methods)
    {
        foreach (var property in BuildPythonProperties(methods))
            AppendPythonProperty(builder, property);
    }

    private static void AppendPythonProperty(StringBuilder builder, PythonProperty property)
    {
        var propertyName = ToSnakeCase(property.Name);
        var annotation = PythonPropertyAnnotation(property);
        var hasSetter = property.Setter is not null;
        var defaultValue = property.Getter?.Method.Property?.DefaultValue;
        if (defaultValue is not null)
        {
            var defaultExpression = PythonPropertyDefaultExpression(property.Getter!, propertyName, defaultValue);
            var returnStatement = hasSetter
                ? $"return getattr(self, \"{PythonBackingFieldName(propertyName)}\", {defaultExpression})"
                : $"return {defaultExpression}";
            _ = builder.AppendLine(
                $"""

                    @property
                    def {propertyName}(self) -> {annotation}:
                        {returnStatement}
                """);

            if (hasSetter)
                AppendPythonPropertySetter(builder, propertyName, annotation, isAbstract: false);
            return;
        }

        if (property.Getter is null)
        {
            _ = builder.AppendLine(
                $"""

                    @property
                    def {propertyName}(self) -> {annotation}:
                        raise AttributeError("{propertyName} is write-only")

                """);
        }
        else
        {
            _ = builder.AppendLine(
                $"""

                    @property
                    @abstractmethod
                    def {propertyName}(self) -> {annotation}:
                        raise NotImplementedError

                """);
        }

        if (hasSetter)
            AppendPythonPropertySetter(builder, propertyName, annotation, isAbstract: true);
    }

    private static void AppendPythonPropertySetter(StringBuilder builder, string propertyName, string annotation, bool isAbstract)
    {
        _ = builder.AppendLine(
            $"""

                @{propertyName}.setter
            """);
        if (isAbstract)
            _ = builder.AppendLine("    @abstractmethod");
        var body = isAbstract
            ? "raise NotImplementedError"
            : $"self.{PythonBackingFieldName(propertyName)} = value";
        _ = builder.AppendLine(
            $"""
                def {propertyName}(self, value: {annotation}) -> None:
                    {body}

            """);
    }

    private static void AppendPythonPropertyCallbackMethods(
        StringBuilder builder,
        IReadOnlyList<MethodWithOwner> methods,
        PidlMetadata metadata)
    {
        foreach (var method in methods.Where(static method => method.Method is { IsOverride: false, PropertyAccessor: PropertyAccessorKind.Getter }))
        {
            if (method.Method.ReturnDictionary is not null)
                AppendPythonReturnDictionaryMethod(builder, method, metadata);
            else if (method.Method.ReturnDateTimeOffset is not null)
                AppendPythonDateTimeOffsetGetterMethod(builder, method, metadata);
        }

        foreach (var method in methods.Where(static method => method.Method is { IsOverride: false, PropertyAccessor: PropertyAccessorKind.Setter }))
            AppendPythonPropertySetterMethod(builder, method, metadata);
    }

    private static void AppendPythonDateTimeOffsetGetterMethod(StringBuilder builder, MethodWithOwner method, PidlMetadata metadata)
    {
        var dateTimeOffset = method.Method.ReturnDateTimeOffset!;
        var parameters = string.Join(", ", method.Method.Parameters.Select(parameter => $"{parameter.Name}: {PythonParameterAnnotation(parameter, metadata)}"));
        var propertyName = ToSnakeCase(method.Method.Property!.Name);
        _ = builder.AppendLine(
            $"""

                def {PythonPrivateMethodName(method.Method.Name)}(self, _self: int, {parameters}) -> int:
                    if not {dateTimeOffset.TicksName} or not {dateTimeOffset.OffsetName}:
                        return _abi.E_POINTER
                    {dateTimeOffset.TicksName}[0], {dateTimeOffset.OffsetName}[0] = self.{propertyName}
                    return _abi.S_OK

            """);
    }

    private static void AppendPythonPropertySetterMethod(StringBuilder builder, MethodWithOwner method, PidlMetadata metadata)
    {
        var parameters = string.Join(", ", method.Method.Parameters.Select(parameter => $"{parameter.Name}: {PythonParameterAnnotation(parameter, metadata)}"));
        var propertyName = ToSnakeCase(method.Method.Property!.Name);
        _ = builder.AppendLine(
            $"""

                def {PythonPrivateMethodName(method.Method.Name)}(self, _self: int, {parameters}) -> int:
                    self.{propertyName} = {PythonPropertySetterValue(method.Method, metadata)}
                    return _abi.S_OK

            """);
    }

    private static string PythonPropertySetterValue(MethodDefinition method, PidlMetadata metadata)
    {
        if (method.DictionaryParameters is [{ } dictionary])
            return PythonReadDictionaryArgument(dictionary);

        if (method.DateTimeOffsetParameters is [{ } dateTimeOffset])
            return $"({dateTimeOffset.TicksName}, {dateTimeOffset.OffsetName})";

        var value = method.Parameters.First(static parameter => !parameter.IsGeneratedArrayCount);
        return PythonReadArgument(method, value, metadata);
    }

    private static string PythonPropertyAnnotation(PythonProperty property)
    {
        if (property.Getter is { } getter)
            return PythonAnnotation(getter.Method);

        return PythonSetterPropertyAnnotation(property.Setter!.Method);
    }

    private static string PythonSetterPropertyAnnotation(MethodDefinition method)
    {
        if (method.DictionaryParameters is [{ } dictionary])
            return PythonDictionaryAnnotation(dictionary);

        if (method.DateTimeOffsetParameters.Count is > 0)
            return PythonType.TupleIntInt;

        var value = method.Parameters.First(static parameter => !parameter.IsGeneratedArrayCount);
        return PythonSdkParameterAnnotation(method, value);
    }

    private static string PythonPropertyDefaultExpression(MethodWithOwner method, string propertyName, string defaultValue)
    {
        return PidlDefaultValueFormatter.Python(defaultValue, method.Method);
    }

    private static string PythonBackingFieldName(string propertyName)
    {
        return "_" + propertyName;
    }

    private static string PythonAnnotation(string pidlType)
    {
        if (pidlType.EndsWith(PidlType.ArraySuffix, StringComparison.Ordinal) ||
            pidlType.EndsWith(PidlType.NullableArraySuffix, StringComparison.Ordinal))
        {
            var elementType = ElementType(pidlType);
            return elementType switch
            {
                PidlType.Byte => PythonType.Bytes,
                _ => PythonType.SequenceOf(PythonAnnotation(elementType))
            };
        }

        return pidlType switch
        {
            PidlType.Bool => PythonType.Bool,
            PidlType.Int or PidlType.UInt or PidlType.Long => PythonType.Int,
            PidlType.Double => PythonType.Float,
            PidlType.String => PythonType.Str,
            PidlType.NullableString => PythonType.StrOrNone,
            PidlType.Symbol => PythonType.Symbol,
            PidlType.IStream => PythonType.AbiStream,
            PidlType.IProgressNotifier => PythonType.AbiProgressNotifier,
            PidlType.ITaskCompletionSource => PythonType.AbiTaskCompletionSource,
            _ when IsInterfaceType(pidlType) => PythonType.AbiComObject,
            _ when pidlType.EndsWith(PidlType.EnumTypeSuffix, StringComparison.Ordinal) => $"_abi.{pidlType}",
            _ => PythonType.Int
        };
    }

    private static string PythonAnnotation(MethodDefinition method)
    {
        if (method.ReturnDictionary is { } dictionary)
            return PythonDictionaryAnnotation(dictionary);

        if (method.ReturnDateTimeOffset is not null)
            return PythonType.TupleIntInt;

        return PythonAnnotation(method.ReturnType);
    }

    private static void AppendPythonValueChangedMethods(StringBuilder builder, MethodWithOwner method, PidlMetadata metadata)
    {
        if (method.Method.Parameters.Count is 1)
        {
            var parameter = method.Method.Parameters[0];
            var annotation = PythonAnnotation(parameter.Type);
            var converter = parameter.Type switch
            {
                PidlType.Bool => PythonBoolToPython(metadata, parameter.Name),
                PidlType.String => $"_abi.read_utf16({parameter.Name})",
                _ => parameter.Name
            };
            _ = builder.AppendLine(
                $"""

                     def on_value_changed(self, value: {annotation}) -> None:
                         self.value = value

                     def _on_value_changed(self, _self: int, {parameter.Name}: {PythonParameterAnnotation(parameter, metadata)}) -> int:
                         self.on_value_changed({converter})
                         return _abi.S_OK

                 """);
        }
        else if (method.Method.Parameters.FirstOrDefault(static parameter => parameter.ArrayCountName is not null) is { } array)
        {
            _ = builder.AppendLine(
                $"""

                     def on_value_changed(self, value: {PythonType.ListOf(PythonType.Str)}) -> None:
                         self.value = value

                     def _on_value_changed(self, _self: int, {array.Name}: int, {array.ArrayCountName}: int) -> int:
                         self.on_value_changed(_abi.read_utf16_array({array.Name}, {array.ArrayCountName}))
                         return _abi.S_OK

                 """);
        }
    }

    private static void AppendPythonDateTimeOffsetMethods(
        StringBuilder builder,
        MethodDefinition? getter,
        MethodDefinition? changed,
        PidlMetadata metadata)
    {
        if (changed?.DateTimeOffsetParameters is [{ } dateTimeOffset])
        {
            _ = builder.AppendLine(
                $"""

                     def on_value_changed(self, {ToSnakeCase(dateTimeOffset.TicksName)}: int, {ToSnakeCase(dateTimeOffset.OffsetName)}: int) -> None:
                         self.value = ({ToSnakeCase(dateTimeOffset.TicksName)}, {ToSnakeCase(dateTimeOffset.OffsetName)})

                 """);
        }

        if (getter?.ReturnDateTimeOffset is { } returnDateTimeOffset)
        {
            var parameters = string.Join(", ", getter.Parameters.Select(parameter => $"{parameter.Name}: {PythonParameterAnnotation(parameter, metadata)}"));
            _ = builder.AppendLine(
                $"""

                     def {PythonPrivateMethodName(getter.Name)}(self, _self: int, {parameters}) -> int:
                         if not {returnDateTimeOffset.TicksName} or not {returnDateTimeOffset.OffsetName}:
                             return _abi.E_POINTER
                         {returnDateTimeOffset.TicksName}[0], {returnDateTimeOffset.OffsetName}[0] = self.default_value
                         return _abi.S_OK

                 """);
        }

        if (changed?.DateTimeOffsetParameters is [{ } value])
        {
            var parameters = string.Join(", ", changed.Parameters.Select(parameter => $"{parameter.Name}: {PythonParameterAnnotation(parameter, metadata)}"));
            _ = builder.AppendLine(
                $"""
                     def {PythonPrivateMethodName(changed.Name)}(self, _self: int, {parameters}) -> int:
                         self.on_value_changed({value.TicksName}, {value.OffsetName})
                         return _abi.S_OK

                 """);
        }
    }

    private static void AppendPythonExtensionMethod(
        StringBuilder builder,
        MethodWithOwner method,
        PidlMetadata metadata,
        MethodWithOwner? asyncResultGetter)
    {
        var methodName = ToSnakeCase(method.Method.Name);
        var skipTask = IsPythonTaskMethod(method.Method);
        var publicParameters = PythonPublicParameters(method.Method, skipTask).ToList();
        var abstractDecorator = method.Method.IsVirtual ? "" : "    @abstractmethod" + Environment.NewLine;
        var body = method.Method.IsVirtual
            ? PythonDefaultBody(method, asyncResultGetter?.Method)
            : "        raise NotImplementedError";
        _ = builder.AppendLine(
            $"""

            {abstractDecorator}    def {methodName}(self{(publicParameters.Count is 0 ? "" : ", " + string.Join(", ", publicParameters))}) -> {PythonReturnAnnotation(method.Method, asyncResultGetter?.Method)}:
            {body}

            """);
        _ = builder.AppendLine(PythonPrivateMethod(method, metadata, asyncResultGetter?.Method));
    }

    private static string PythonDefaultBody(MethodWithOwner method, MethodDefinition? asyncResultGetter)
    {
        if (method.Method.Name is "TransformAsync" && method.Method.Parameters.Any(static parameter => parameter.IsBuiltInStream))
            return "        original_stream.copy_to(destination_stream)";
        if (asyncResultGetter is not null)
            return PythonDefaultReturnBody(asyncResultGetter);
        if (method.Method.ReturnType is not PidlType.Void)
            return PythonDefaultReturnBody(method.Method);
        return "        pass";
    }

    private static string PythonDefaultReturnBody(MethodDefinition method)
    {
        if (method.ReturnDictionary is not null)
            return "        return {}";

        if (method.ReturnDateTimeOffset is not null)
            return "        return (0, 0)";

        if (method.ReturnArrayCountName is not null)
        {
            return method.ReturnType switch
            {
                PidlType.ByteArray or PidlType.NullableByteArray => "        return b\"\"",
                _ => "        return []"
            };
        }

        return method.ReturnType switch
        {
            PidlType.String or PidlType.NullableString => "        return \"\"",
            PidlType.Bool => "        return False",
            PidlType.IStream => $"        return {PythonType.AbiStream}(None)",
            _ => "        return 0"
        };
    }

    private static string PythonPrivateMethod(
        MethodWithOwner method,
        PidlMetadata metadata,
        MethodDefinition? asyncResultGetter)
    {
        var privateName = PythonPrivateMethodName(method.Method.Name);
        var parameters = method.Method.Parameters.Select(parameter => $"{parameter.Name}: {PythonParameterAnnotation(parameter, metadata)}").ToList();
        if (method.Method.ReturnType is not PidlType.Void)
            parameters.Add($"result: {PythonCallbackReturnType(method.Method, metadata)}");
        var builder = new StringBuilder();
        _ = builder.AppendLine($"    def {privateName}(self, _self: int{(parameters.Count is 0 ? "" : ", " + string.Join(", ", parameters))}) -> int:");
        if (method.Method.Name is "OnExtensionLoaded")
            _ = builder.AppendLine("        self.loaded = True");
        else if (method.Method.Name is "OnExtensionUnloaded")
            _ = builder.AppendLine("        self.loaded = False");
        var callArguments = PythonCallArguments(method.Method, metadata, IsPythonTaskMethod(method.Method)).ToList();
        var call = $"{ToSnakeCase(method.Method.Name)}({string.Join(", ", callArguments)})";
        if (asyncResultGetter is not null)
        {
            _ = builder.AppendLine(
                $"""
                        value = self.{call}
                        self.{PythonAsyncResultFieldName(asyncResultGetter)} = value
                        _complete_task(task)
                        return _abi.S_OK
                """);
            return builder.ToString().TrimEnd();
        }

        if (method.Method.ReturnType is PidlType.Void)
        {
            var taskCompletionLine = method.Method.Parameters.Any(static parameter => parameter.Name is "task")
                ? "        _complete_task(task)" + Environment.NewLine
                : "";
            _ = builder.AppendLine(
                $"""
                        self.{call}
                {taskCompletionLine}        return _abi.S_OK
                """);
        }
        else
        {
            _ = builder.AppendLine(
                $"""
                        value = self.{call}
                        return {PythonCopyReturnValue(method.Method.ReturnType, "value", "result", metadata)}
                """);
        }

        return builder.ToString().TrimEnd();
    }

    private static void AppendPythonAsyncResultGetter(StringBuilder builder, MethodWithOwner method, PidlMetadata metadata)
    {
        var privateName = PythonPrivateMethodName(method.Method.Name);
        var parameters = method.Method.Parameters.Select(parameter => $"{parameter.Name}: {PythonParameterAnnotation(parameter, metadata)}").ToList();
        if (method.Method.ReturnType is not PidlType.Void)
            parameters.Add($"result: {PythonCallbackReturnType(method.Method, metadata)}");
        var fieldName = PythonAsyncResultFieldName(method.Method);

        _ = builder.AppendLine(
            $"""

                def {privateName}(self, _self: int{(parameters.Count is 0 ? "" : ", " + string.Join(", ", parameters))}) -> int:
                    value = getattr(self, "{fieldName}", {PythonDefaultValue(method.Method)})
            """);
        _ = builder.AppendLine(PythonCopyAsyncResultLines(method.Method, "value", metadata));
    }

    private static string PythonBoolReturnCallback(PidlMetadata metadata, string value)
    {
        return metadata.BoolMarshalling switch
        {
            UnmanagedType.Bool => $"IntReturnCallback(lambda _self, result: _copy_int({PythonBoolToAbi(metadata, value)}, result))",
            _ => throw new ArgumentOutOfRangeException(nameof(metadata))
        };
    }

    private static string PythonBoolAbiType(PidlMetadata metadata)
    {
        return metadata.BoolMarshalling switch
        {
            UnmanagedType.Bool => PythonType.AbiInt32,
            _ => throw new ArgumentOutOfRangeException(nameof(metadata))
        };
    }

    private static string PythonBoolToAbi(PidlMetadata metadata, string value)
    {
        return metadata.BoolMarshalling switch
        {
            UnmanagedType.Bool => $"(1 if {value} else 0)",
            _ => throw new ArgumentOutOfRangeException(nameof(metadata))
        };
    }

    private static string PythonBoolToPython(PidlMetadata metadata, string value)
    {
        return metadata.BoolMarshalling switch
        {
            UnmanagedType.Bool => $"({value} != 0)",
            _ => throw new ArgumentOutOfRangeException(nameof(metadata))
        };
    }

    private static string PythonParameterAnnotation(ParameterDefinition parameter, PidlMetadata metadata)
    {
        if (parameter.IsOut)
        {
            return parameter.Type switch
            {
                PidlType.Int => Pointer(PythonType.AbiInt32),
                PidlType.Long => Pointer(PythonType.AbiInt64),
                PidlType.UInt => Pointer(PythonType.AbiUInt32),
                PidlType.Double => Pointer(PythonType.AbiDouble),
                _ => Pointer(PythonType.AbiVoidPointer)
            };
        }

        return parameter.Type switch
        {
            PidlType.Bool => PythonBoolAbiType(metadata),
            _ => PythonType.Int
        };
    }

    private static string PythonCopyReturnValue(string returnType, string value, string result, PidlMetadata metadata)
    {
        return returnType switch
        {
            PidlType.String or PidlType.NullableString => $"_abi.copy_utf16({value}, {result})",
            PidlType.Bool => $"_copy_int({PythonBoolToAbi(metadata, value)}, {result})",
            PidlType.Int => $"_copy_int({value}, {result})",
            PidlType.UInt => $"_copy_uint({value}, {result})",
            PidlType.Double => $"_copy_double({value}, {result})",
            PidlType.Symbol => $"_copy_int(int({value}), {result})",
            _ when returnType.EndsWith(PidlType.EnumTypeSuffix, StringComparison.Ordinal) => $"_copy_int(int({value}), {result})",
            _ => $"_copy_int(int({value}), {result})"
        };
    }

    private static string PythonCopyAsyncResultLines(MethodDefinition method, string value, PidlMetadata metadata)
    {
        if (method.ReturnDictionary is { } dictionary)
        {
            return
                $"""
                     keys = list({value}.keys())
                     items = list({value}.values())
                     hr = {PythonCopyDictionaryElement(dictionary.KeyType, "keys", dictionary.CountName, dictionary.KeysName)}
                     if hr != _abi.S_OK:
                         return hr
                     {dictionary.CountName}[0] = len(value)
                     return {PythonCopyDictionaryElement(dictionary.ValueType, "items", "", dictionary.ValuesName)}
                 """;
        }

        if (method.ReturnDateTimeOffset is { } dateTimeOffset)
        {
            return
                $"""
                     if not {dateTimeOffset.TicksName} or not {dateTimeOffset.OffsetName}:
                         return _abi.E_POINTER
                     {dateTimeOffset.TicksName}[0], {dateTimeOffset.OffsetName}[0] = {value}
                     return _abi.S_OK
                 """;
        }

        if (method.ReturnArrayCountName is { } returnCountName)
        {
            return $"    return {PythonCopyArrayReturnValue(method.ReturnType, value, returnCountName, "result")}";
        }

        if (method is { ReturnIsBuiltInStream: true, ReturnType: PidlType.IStream })
        {
            return
                $"""
                     if not result:
                         return _abi.E_POINTER
                     result[0] = {value}.native
                     return _abi.S_OK
                 """;
        }

        return $"    return {PythonCopyReturnValue(method.ReturnType, value, "result", metadata)}";
    }

    private static string PythonCopyArrayReturnValue(string returnType, string value, string count, string result)
    {
        return ElementType(returnType) switch
        {
            PidlType.String => $"_abi.copy_utf16_array({value}, {count}, {result})",
            PidlType.Byte => $"_abi.copy_bytes({value} or b\"\", {count}, {result})",
            PidlType.Int => $"_abi.copy_int32_array({value}, {result})",
            PidlType.IStream => $"_abi.copy_pointer_array((stream.native for stream in {value}), {count}, {result})",
            PidlType.IExtension => $"_abi.copy_pointer_array((extension.export() for extension in {value}), {count}, {result})",
            _ => $"_abi.copy_pointer_array({value}, {count}, {result})"
        };
    }

    private static string PythonDefaultValue(MethodDefinition method)
    {
        if (method.ReturnDictionary is not null)
            return "{}";

        if (method.ReturnDateTimeOffset is not null)
            return "(0, 0)";

        if (method.ReturnArrayCountName is not null)
        {
            return method.ReturnType switch
            {
                PidlType.ByteArray or PidlType.NullableByteArray => "b\"\"",
                _ => "[]"
            };
        }

        return method.ReturnType switch
        {
            PidlType.String or PidlType.NullableString => "\"\"",
            PidlType.Bool => "False",
            PidlType.IStream => $"{PythonType.AbiStream}(None)",
            _ => "0"
        };
    }

    private static string PythonReadArgument(MethodDefinition method, ParameterDefinition parameter, PidlMetadata metadata)
    {
        if (parameter.ArrayCountName is { } countName)
        {
            var elementType = ElementType(parameter.Type);
            return elementType switch
            {
                PidlType.String => $"_abi.read_utf16_array({parameter.Name}, {countName})",
                PidlType.IStream => $"[{PythonType.AbiStream}(pointer) for pointer in _abi.read_pointer_array({parameter.Name}, {countName})]",
                PidlType.Int => $"_abi.read_int32_array({parameter.Name}, {countName})",
                _ => $"_abi.read_pointer_array({parameter.Name}, {countName})"
            };
        }

        return parameter.Type switch
        {
            PidlType.String or PidlType.NullableString => $"_abi.read_utf16({parameter.Name})",
            PidlType.Bool => PythonBoolToPython(metadata, parameter.Name),
            PidlType.IStream => $"{PythonType.AbiStream}({parameter.Name})",
            PidlType.IProgressNotifier => $"{PythonType.AbiProgressNotifier}({parameter.Name})",
            PidlType.ITaskCompletionSource => $"{PythonType.AbiTaskCompletionSource}({parameter.Name})",
            _ when parameter.Type.EndsWith(PidlType.EnumTypeSuffix, StringComparison.Ordinal) => $"_abi.{parameter.Type}({parameter.Name})",
            _ => parameter.Name
        };
    }

    private static string PythonSdkParameterAnnotation(MethodDefinition method, ParameterDefinition parameter)
    {
        if (parameter.ArrayCountName is not null)
            return PythonType.ListOf(PythonAnnotation(ElementType(parameter.Type)));

        return parameter.Type switch
        {
            PidlType.IStream => PythonType.AbiStream,
            PidlType.IProgressNotifier => PythonType.AbiProgressNotifier,
            _ => PythonAnnotation(parameter.Type)
        };
    }

    private static string PythonReturnAnnotation(MethodDefinition method)
    {
        return method.ReturnType is PidlType.Void ? PythonType.None : PythonAnnotation(method.ReturnType);
    }

    private static string PythonReturnAnnotation(MethodDefinition method, MethodDefinition? asyncResultGetter)
    {
        if (asyncResultGetter is not null)
            return PythonAnnotation(asyncResultGetter);

        return PythonReturnAnnotation(method);
    }

    private static bool IsPythonTaskMethod(MethodDefinition method)
    {
        return method.IsAsync;
    }

    private static MethodWithOwner? FindAsyncResultGetter(IReadOnlyList<MethodWithOwner> methods, MethodDefinition taskMethod)
    {
        return methods
            .FirstOrDefault(method => ReferenceEquals(method.Method.AsyncResultGetter?.SourceMethod, taskMethod));
    }

    private static void AppendPythonReturnDictionaryMethod(StringBuilder builder, MethodWithOwner method, PidlMetadata metadata)
    {
        var dictionary = method.Method.ReturnDictionary!;
        var propertyName = ToSnakeCase(method.Method.Property!.Name);
        var parameters = string.Join(", ", method.Method.Parameters.Select(parameter => $"{parameter.Name}: {PythonParameterAnnotation(parameter, metadata)}"));
        _ = builder.AppendLine(
            $"""

                 def {PythonPrivateMethodName(method.Method.Name)}(self, _self: int, {parameters}) -> int:
                     values = self.{propertyName}
                     keys = list(values.keys())
                     items = list(values.values())
                     hr = {PythonCopyDictionaryElement(dictionary.KeyType, "keys", dictionary.CountName, dictionary.KeysName)}
                     if hr != _abi.S_OK:
                         return hr
                     {dictionary.CountName}[0] = len(values)
                     return {PythonCopyDictionaryElement(dictionary.ValueType, "items", "", dictionary.ValuesName)}

             """);
    }

    private static IEnumerable<string> PythonPublicParameters(MethodDefinition method, bool skipTask)
    {
        var start = skipTask ? 1 : 0;
        for (var i = start; i < method.Parameters.Count; ++i)
        {
            if (TryMatchDictionaryExpansion(method, i, out var dictionary))
            {
                yield return $"{PythonIdentifier(ToSnakeCase(dictionary.Name))}: {PythonDictionaryAnnotation(dictionary)}";
                ++i;
                continue;
            }

            var parameter = method.Parameters[i];
            if (parameter.IsGeneratedArrayCount)
                continue;

            yield return $"{PythonIdentifier(ToSnakeCase(parameter.Name))}: {PythonSdkParameterAnnotation(method, parameter)}";
        }
    }

    private static IEnumerable<string> PythonCallArguments(MethodDefinition method, PidlMetadata metadata, bool skipTask)
    {
        var start = skipTask ? 1 : 0;
        for (var i = start; i < method.Parameters.Count; ++i)
        {
            if (TryMatchDictionaryExpansion(method, i, out var dictionary))
            {
                yield return PythonReadDictionaryArgument(dictionary);
                ++i;
                continue;
            }

            var parameter = method.Parameters[i];
            if (parameter.IsGeneratedArrayCount)
                continue;

            yield return PythonReadArgument(method, parameter, metadata);
        }
    }

    private static bool TryMatchDictionaryExpansion(MethodDefinition method, int index, out DictionaryExpansion dictionary)
    {
        dictionary = null!;
        if (index + 1 >= method.Parameters.Count)
            return false;

        var keys = method.Parameters[index];
        var values = method.Parameters[index + 1];
        var match = method.DictionaryParameters.FirstOrDefault(expansion =>
            expansion.KeysName == keys.Name &&
            expansion.ValuesName == values.Name);
        if (match is null)
            return false;

        dictionary = match;
        return true;
    }

    private static string PythonReadDictionaryArgument(DictionaryExpansion dictionary)
    {
        var keys = PythonReadDictionaryElement(dictionary.KeyType, dictionary.KeysName, dictionary.CountName);
        var values = PythonReadDictionaryElement(dictionary.ValueType, dictionary.ValuesName, dictionary.CountName);
        return $"dict(zip({keys}, {values}))";
    }

    private static string PythonReadDictionaryElement(string type, string name, string countName)
    {
        return type switch
        {
            PidlType.String => $"_abi.read_utf16_array({name}, {countName})",
            PidlType.IStream => $"[{PythonType.AbiStream}(pointer) for pointer in _abi.read_pointer_array({name}, {countName})]",
            PidlType.Int => $"_abi.read_int32_array({name}, {countName})",
            _ => $"_abi.read_pointer_array({name}, {countName})"
        };
    }

    private static string PythonDictionaryAnnotation(DictionaryExpansion dictionary)
    {
        return $"dict[{PythonDictionaryElementAnnotation(dictionary.KeyType)}, {PythonDictionaryElementAnnotation(dictionary.ValueType)}]";
    }

    private static string PythonDictionaryElementAnnotation(string type)
    {
        return type is PidlType.IStream ? PythonType.AbiStream : PythonAnnotation(type);
    }

    private static string PythonCopyDictionaryElement(string type, string values, string count, string result)
    {
        return type switch
        {
            PidlType.String => $"_abi.copy_utf16_array({values}, {count}, {result})",
            PidlType.Int => $"_abi.copy_int32_array({values}, {result})",
            _ => $"_abi.copy_pointer_array((value.native for value in {values}), {count}, {result})"
        };
    }

    private static string PythonPrivateMethodName(string name)
    {
        return "_" + ToSnakeCase(name);
    }

    private static string PythonAsyncResultFieldName(MethodDefinition resultGetter)
    {
        return "_" + ToSnakeCase(GetAsyncResultFieldStem(resultGetter.Name));
    }

    private static string GetAsyncResultFieldStem(string methodName)
    {
        if (methodName.Length > 3 &&
            methodName.StartsWith("Get", StringComparison.Ordinal))
            return methodName[3..];

        return methodName;
    }

    private static string PythonIidList(IEnumerable<InterfaceDefinition> interfaces)
    {
        return string.Join(", ", ["_abi.IID_IUNKNOWN", .. interfaces.Select(static value => "_abi.IID_" + ConstantName(value))]);
    }

    private static string PythonSdkClassName(InterfaceDefinition definition)
    {
        var sdkName = definition.SdkName ?? ShortName(definition.FullName);
        return sdkName.EndsWith("Base", StringComparison.Ordinal) ? sdkName[..^"Base".Length] : sdkName;
    }

    private static IReadOnlyList<InterfaceDefinition> OrderPythonSdkDefinitions(PythonModelContext context, PidlModel model)
    {
        var definitions = model.Interfaces
            .Where(static definition => definition.SdkName is not null)
            .ToList();
        var pending = definitions.ToHashSet();
        var ordered = new List<InterfaceDefinition>();

        while (pending.Count > 0)
        {
            var added = false;
            foreach (var definition in pending.ToList())
            {
                var baseInterface = context.ResolveSdkBaseInterface(definition);
                if (baseInterface is not null && pending.Contains(baseInterface))
                    continue;

                ordered.Add(definition);
                _ = pending.Remove(definition);
                added = true;
            }

            if (!added)
                throw new InvalidOperationException("A cycle was found in Python SDK base definitions.");
        }

        return ordered;
    }

    private static string ElementType(string type)
    {
        if (type.EndsWith(PidlType.NullableArraySuffix, StringComparison.Ordinal))
            return type[..^3];

        return type.EndsWith(PidlType.ArraySuffix, StringComparison.Ordinal) ? type[..^2] : type;
    }

    private static bool IsInterfaceType(string type)
    {
        return type.Length > 1 &&
               type[0] is 'I' &&
               char.IsUpper(type[1]) &&
               !type.EndsWith(PidlType.ArraySuffix, StringComparison.Ordinal);
    }

    private sealed class PythonProperty(string name)
    {
        public string Name { get; } = name;

        public MethodWithOwner? Getter { get; set; }

        public MethodWithOwner? Setter { get; set; }
    }

    private static void AppendSdkPresetManifest(StringBuilder builder, PidlModel model)
    {
        var presets = model.Interfaces
            .Where(static definition => definition.SdkName is not null)
            .Select(static definition => definition.SdkName!)
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .ToList();

        _ = builder.AppendLine("# PIDL SDK presets available in this package:");
        foreach (var preset in presets)
            _ = builder.AppendLine($"# - {preset}");
    }

    private static string ConstantName(InterfaceDefinition definition)
    {
        var name = ShortName(definition.FullName);
        if (name.StartsWith('I') && name.Length > 1 && char.IsUpper(name[1]))
            name = name[1..];

        return ToSnakeCase(name).ToUpperInvariant();
    }

    private static string PythonIdentifier(string value)
    {
        return _PythonKeywords.Contains(value) ? value + "_" : value;
    }

    private static string ToSnakeCase(string value)
    {
        var builder = new StringBuilder();
        for (var i = 0; i < value.Length; i++)
        {
            var current = value[i];
            if (char.IsUpper(current) && i > 0)
                _ = builder.Append('_');
            _ = builder.Append(char.ToLowerInvariant(current));
        }

        return builder.ToString();
    }

    private static string ShortName(string fullName)
    {
        var separator = fullName.LastIndexOf('.');
        return separator < 0 ? fullName : fullName[(separator + 1)..];
    }

    private sealed class PythonModelContext
    {
        private readonly Dictionary<string, InterfaceDefinition> _interfaces;

        public PythonModelContext(PidlModel model)
        {
            _interfaces = model.Interfaces
                .SelectMany(static definition => new[]
                {
                    new KeyValuePair<string, InterfaceDefinition>(definition.FullName, definition),
                    new KeyValuePair<string, InterfaceDefinition>(ShortName(definition.FullName), definition)
                })
                .GroupBy(static pair => pair.Key, StringComparer.Ordinal)
                .ToDictionary(static group => group.Key, static group => group.First().Value, StringComparer.Ordinal);

            InterfacesWithGuid = model.Interfaces.Where(static definition => definition.Guid is not null).ToList();
        }

        public IReadOnlyList<InterfaceDefinition> InterfacesWithGuid { get; }

        public InterfaceDefinition RequireInterface(string name)
        {
            if (_interfaces.TryGetValue(name, out var definition))
                return definition;

            throw new InvalidOperationException($"Interface '{name}' was not found in PIDL.");
        }

        public InterfaceDefinition? ResolveSdkBaseInterface(InterfaceDefinition definition)
        {
            if (definition.Inherits is null)
                return null;

            var current = RequireInterface(definition.Inherits);
            while (true)
            {
                if (current.SdkName is not null)
                    return current;

                if (current.Inherits is null)
                    return null;

                current = RequireInterface(current.Inherits);
            }
        }

        public IReadOnlyList<InterfaceDefinition> FlattenInterfaces(InterfaceDefinition definition)
        {
            var result = new List<InterfaceDefinition>();
            AppendInterfaceChain(definition, result);
            return result;
        }

        public IReadOnlyList<MethodWithOwner> FlattenMethods(InterfaceDefinition definition, bool includeOverrides = true)
        {
            return FlattenInterfaces(definition)
                .SelectMany(static owner => owner.Methods.Select(method => new MethodWithOwner(owner, method)))
                .Where(method => includeOverrides || !method.Method.IsOverride)
                .ToList();
        }

        private void AppendInterfaceChain(InterfaceDefinition definition, List<InterfaceDefinition> result)
        {
            if (definition.Inherits is not null)
                AppendInterfaceChain(RequireInterface(definition.Inherits), result);

            result.Add(definition);
        }
    }

    private sealed record MethodWithOwner(InterfaceDefinition Owner, MethodDefinition Method);
}
