using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Pixeval.Extensions.Generator;

internal static class CppEmitter
{
    private const string ExtensionSuffix = "Extension";
    private const string SettingsExtensionSuffix = "SettingsExtension";
    private const string ImageFormatProviderSuffix = "ImageFormatProvider";
    private const string TransformerCommandSuffix = "TransformerCommand";

    private static readonly Dictionary<string, SettingNameMapping> _SettingNameMappings = new(StringComparer.Ordinal)
    {
        ["Bool"] = new("boolean", "bool"),
        ["Int"] = new("integer", "int"),
        ["Double"] = new("floating", "double"),
        ["String"] = new("text", "string"),
        ["StringsArray"] = new("text_array", "strings_array"),
        ["Enum"] = new("enumeration", "int", "enum"),
        ["Color"] = new("color", "color"),
        ["DateTimeOffset"] = new("date_time_offset", "date_time_offset")
    };

    public static string EmitCommon(PidlModel model)
    {
        var context = new CppModelContext(model);
        var builder = new StringBuilder();
        _ = builder.AppendLine(
            """
            // <auto-generated />
            #pragma once
            #include <pixeval/detail/runtime.hpp>

            namespace pixeval::extensions
            {
            """);
        AppendAbiConfiguration(builder, model);
        AppendIids(builder, context);
        AppendEnums(builder, model);
        AppendSlots(builder, context);
        AppendSupportFunctions(builder, context);
        _ = builder.AppendLine("}");
        return builder.ToString();
    }

    public static string EmitSdk(PidlModel model)
    {
        var context = new CppModelContext(model);
        var builder = new StringBuilder();
        _ = builder.AppendLine(
            """
            // <auto-generated />
            #pragma once

            """);
        _ = builder.Append(EmitVtables(context));
        return builder.ToString();
    }

    private static void AppendAbiConfiguration(StringBuilder builder, PidlModel model)
    {
        _ = builder.AppendLine(
            $$"""
            namespace abi
            {
                inline constexpr std::u16string_view sdk_version = u"{{model.SdkVersion}}";
                using bool_abi = {{CppBoolAbiType(model.Metadata)}};
                inline constexpr bool_abi bool_false = {{CppBoolFalse(model.Metadata)}};

                [[nodiscard]] inline bool bool_from_abi(bool_abi value) noexcept
                {
                    return {{CppBoolToCpp(model.Metadata, "value")}};
                }

                [[nodiscard]] inline bool_abi bool_to_abi(bool value) noexcept
                {
                    return {{CppBoolFromCpp(model.Metadata, "value")}};
                }
            }

            """);
    }

    private static string CppBoolAbiType(PidlMetadata metadata)
    {
        return metadata.BoolMarshalling switch
        {
            BoolMarshallingMode.BOOL => "std::int32_t",
            _ => throw new ArgumentOutOfRangeException(nameof(metadata))
        };
    }

    private static string CppBoolFalse(PidlMetadata metadata)
    {
        return metadata.BoolMarshalling switch
        {
            BoolMarshallingMode.BOOL => "0",
            _ => throw new ArgumentOutOfRangeException(nameof(metadata))
        };
    }

    private static string CppBoolFromCpp(PidlMetadata metadata, string expression)
    {
        return metadata.BoolMarshalling switch
        {
            BoolMarshallingMode.BOOL => $"({expression} ? 1 : 0)",
            _ => throw new ArgumentOutOfRangeException(nameof(metadata))
        };
    }

    private static string CppBoolToCpp(PidlMetadata metadata, string expression)
    {
        return metadata.BoolMarshalling switch
        {
            BoolMarshallingMode.BOOL => $"({expression} != 0)",
            _ => throw new ArgumentOutOfRangeException(nameof(metadata))
        };
    }

    private static string EmitVtables(CppModelContext context)
    {
        var builder = new StringBuilder();
        var hostVtable = context.HostVtable;
        var extensionVtables = context.ExtensionVtables;
        var settingVtables = context.SettingVtables;

        AppendVtable(builder, context, hostVtable);
        foreach (var vtable in extensionVtables)
            AppendVtable(builder, context, vtable);
        foreach (var vtable in settingVtables)
            AppendVtable(builder, context, vtable);

        AppendVtableFor(builder, "setting_kind", settingVtables, static vtable => vtable.SettingKind!);
        AppendVtableFor(builder, "extension_kind", extensionVtables, static vtable => vtable.ExtensionKind!);
        return builder.ToString();
    }

    private static void AppendIids(StringBuilder builder, CppModelContext context)
    {
        _ = builder.AppendLine(
            """
            namespace abi
            {
                constexpr guid iid_iunknown{0x00000000, 0x0000, 0x0000, {0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46}};
            """);
        foreach (var definition in context.InterfacesWithGuid)
            _ = builder.AppendLine($"    constexpr guid iid_{AbiName(definition)}{FormatGuid(definition.Guid!)};");
        _ = builder.AppendLine(
            """
            }

            """);
    }

    private static void AppendEnums(StringBuilder builder, PidlModel model)
    {
        foreach (var definition in model.Enums)
        {
            _ = builder.AppendLine(
                $$"""
                enum class {{ShortName(definition.FullName)}} : std::int32_t
                {
                """);
            var nextValue = 0;
            foreach (var value in definition.Values)
            {
                var actualValue = value.Value ?? nextValue.ToString();
                _ = builder.AppendLine($"    {value.Name} = {actualValue},");
                if (int.TryParse(actualValue, out var parsed))
                    nextValue = parsed + 1;
                else
                    ++nextValue;
            }

            _ = builder.AppendLine(
                """
                };

                """);
        }
    }

    private static void AppendSlots(StringBuilder builder, CppModelContext context)
    {
        _ = builder.AppendLine(
            """
            namespace abi
            {
            """);
        foreach (var definition in context.InterfacesWithGuid)
        {
            _ = builder.AppendLine(
                $$"""
                    enum class {{AbiName(definition)}}_slot : std::int32_t
                    {
                        query_interface = 0,
                        add_ref = 1,
                        release = 2,
                """);

            var slot = 3;
            foreach (var method in context.FlattenMethods(definition))
                _ = builder.AppendLine($"        {ToSnakeCase(method.Method.Name)} = {slot++},");

            _ = builder.AppendLine(
                """
                    };

                """);
        }

        _ = builder.AppendLine(
            """
            }

            """);
    }

    private static void AppendSupportFunctions(StringBuilder builder, CppModelContext context)
    {
        _ = builder.AppendLine(
            """
            namespace abi
            {
            """);
        foreach (var definition in context.InterfacesWithGuid)
        {
            _ = builder.AppendLine(
                $$"""
                    [[nodiscard]] inline bool supports_{{AbiName(definition)}}(const guid& iid) noexcept
                    {
                """);

            var supported = context.FlattenInterfaces(definition)
                .Where(static value => value.Guid is not null)
                .Select(static value => $"iid_{AbiName(value)}")
                .ToList();

            _ = builder.AppendLine(
                "        return iid == iid_iunknown ||");
            for (var i = 0; i < supported.Count; i++)
            {
                var terminator = i == supported.Count - 1 ? ";" : " ||";
                _ = builder.AppendLine($"               iid == {supported[i]}{terminator}");
            }

            _ = builder.AppendLine(
                """
                    }

                """);
        }

        _ = builder.AppendLine(
            """
            }

            """);
    }

    private static void AppendVtable(StringBuilder builder, CppModelContext context, ConcreteVtable vtable)
    {
        var definition = context.RequireInterface(vtable.InterfaceName);
        _ = builder.AppendLine(
            $$"""
            inline void* {{vtable.Name}}[] = {
                reinterpret_cast<void*>(&{{ThunkPrefix(vtable)}}_query_interface),
                reinterpret_cast<void*>(&{{ThunkPrefix(vtable)}}_add_ref),
                reinterpret_cast<void*>(&{{ThunkPrefix(vtable)}}_release),
            """);

        foreach (var method in context.FlattenMethods(definition))
            _ = builder.AppendLine($"    reinterpret_cast<void*>(&{ThunkName(vtable, method)}),");

        TrimLastComma(builder);
        _ = builder.AppendLine(
            """
            };

            """);
    }

    private static void AppendVtableFor(
        StringBuilder builder,
        string kindType,
        IReadOnlyList<ConcreteVtable> vtables,
        Func<ConcreteVtable, string> kindSelector)
    {
        _ = builder.AppendLine(
            $$"""
            [[nodiscard]] inline void** vtable_for({{kindType}} kind) noexcept
            {
                switch (kind)
                {
            """);
        foreach (var vtable in vtables)
            _ = builder.AppendLine($"    case {kindSelector(vtable)}: return {vtable.Name};");
        _ = builder.AppendLine(
            $$"""
                }

                return {{vtables[0].Name}};
            }

            """);
    }

    private static string ThunkName(ConcreteVtable vtable, MethodWithOwner method)
    {
        if (vtable.SettingKind is not null)
            return SettingThunkName(vtable, method);
        if (vtable.ExtensionKind is not null)
            return ExtensionThunkName(method);

        return $"{ThunkPrefix(vtable)}_{ToSnakeCase(method.Method.Name)}";
    }

    private static string ExtensionThunkName(MethodWithOwner method)
    {
        var ownerStem = InterfaceStem(method.Owner.FullName, ExtensionSuffix);
        if (method.Method.Name is "FormatImage" &&
            TrimSuffix(ownerStem, ImageFormatProviderSuffix) is { Length: > 0 } imageKind)
            return $"extension_format_{ToSnakeCase(imageKind)}_image";
        if (method.Method.Name is "TransformAsync" &&
            TrimSuffix(ownerStem, TransformerCommandSuffix) is { Length: > 0 } transformKind)
            return $"extension_transform_{ToSnakeCase(transformKind)}";

        return $"extension_{ToSnakeCase(method.Method.Name)}";
    }

    private static string SettingThunkName(ConcreteVtable vtable, MethodWithOwner method)
    {
        var mapping = SettingNameMappingFor(vtable.InterfaceName);
        return method.Method.Name switch
        {
            "GetDefaultValue" => $"setting_get_{mapping.ValueThunkPrefix}_default",
            "OnValueChanged" => $"setting_on_{mapping.ValueThunkPrefix}_value_changed",
            "GetMinValue" => $"setting_get_{mapping.ValueThunkPrefix}_min",
            "GetMaxValue" => $"setting_get_{mapping.ValueThunkPrefix}_max",
            "GetStepValue" => $"setting_get_{mapping.ValueThunkPrefix}_step",
            "GetEnumKeyValues" => $"setting_get_{mapping.SpecializedThunkPrefix}_key_values",
            _ => $"setting_{ToSnakeCase(method.Method.Name)}"
        };
    }

    private static string ThunkPrefix(ConcreteVtable vtable)
    {
        if (vtable.InterfaceName is "IExtensionsHost")
            return "host";

        return vtable.SettingKind is null ? "extension" : "setting";
    }

    private static string FormatGuid(string value)
    {
        var parts = Guid.Parse(value).ToString("D").Split('-');
        var data4 = parts[3] + parts[4];
        var bytes = Enumerable.Range(0, 8)
            .Select(index => "0x" + data4.Substring(index * 2, 2).ToUpperInvariant());

        return $"{{0x{parts[0].ToUpperInvariant()}, 0x{parts[1].ToUpperInvariant()}, 0x{parts[2].ToUpperInvariant()}, {{{string.Join(", ", bytes)}}}}}";
    }

    private static string AbiName(InterfaceDefinition definition)
    {
        var name = ShortName(definition.FullName);
        if (name.StartsWith('I') && name.Length > 1 && char.IsUpper(name[1]))
            name = name[1..];

        return ToSnakeCase(name);
    }

    private static string ToSnakeCase(string value)
    {
        var builder = new StringBuilder();
        for (var i = 0; i < value.Length; i++)
        {
            var current = value[i];
            if (char.IsUpper(current) && i > 0)
                _ = builder.Append('_');
            _ = builder.Append(char.ToLowerInvariant(current));
        }

        return builder.ToString();
    }

    private static SettingNameMapping SettingNameMappingFor(string interfaceName)
    {
        var stem = InterfaceStem(interfaceName, SettingsExtensionSuffix);
        return _SettingNameMappings.TryGetValue(stem, out var mapping)
            ? mapping
            : new SettingNameMapping(ToSnakeCase(stem), ToSnakeCase(stem));
    }

    private static string InterfaceStem(string interfaceName, string suffix)
    {
        var name = ShortName(interfaceName);
        if (name.StartsWith('I') && name.Length > 1 && char.IsUpper(name[1]))
            name = name[1..];
        if (name.EndsWith(suffix, StringComparison.Ordinal))
            name = name[..^suffix.Length];
        return name;
    }

    private static string? TrimSuffix(string value, string suffix)
    {
        return value.EndsWith(suffix, StringComparison.Ordinal) ? value[..^suffix.Length] : null;
    }

    private static string ShortName(string fullName)
    {
        var separator = fullName.LastIndexOf('.');
        return separator < 0 ? fullName : fullName[(separator + 1)..];
    }

    private static void TrimLastComma(StringBuilder builder)
    {
        for (var i = builder.Length - 1; i >= 0; i--)
        {
            if (builder[i] is not ',')
                continue;

            _ = builder.Remove(i, 1);
            return;
        }
    }

    private sealed class CppModelContext
    {
        private readonly Dictionary<string, InterfaceDefinition> _interfaces;

        public CppModelContext(PidlModel model)
        {
            _interfaces = model.Interfaces
                .SelectMany(static definition => new[]
                {
                    new KeyValuePair<string, InterfaceDefinition>(definition.FullName, definition),
                    new KeyValuePair<string, InterfaceDefinition>(ShortName(definition.FullName), definition)
                })
                .GroupBy(static pair => pair.Key, StringComparer.Ordinal)
                .ToDictionary(static group => group.Key, static group => group.First().Value, StringComparer.Ordinal);

            InterfacesWithGuid = model.Interfaces.Where(static definition => definition.Guid is not null).ToList();
            HostVtable = new ConcreteVtable("host_vtable", "IExtensionsHost", null, null);
            SettingVtables = model.Interfaces
                .Where(definition => definition.SdkName is not null && !IsSdkAbstract(definition) && IsSettingsInterface(definition))
                .Select(definition => new ConcreteVtable(
                    $"{ToSnakeCase(SettingsKindName(definition))}_setting_vtable",
                    ShortName(definition.FullName),
                    null,
                    $"setting_kind::{SettingsKindName(definition)}"))
                .ToList();
            ExtensionVtables = model.Interfaces
                .Where(definition => definition.SdkName is not null &&
                                     !IsSdkAbstract(definition) &&
                                     definition.Special is not "ExtensionsHostStatics" &&
                                     ShortName(definition.FullName) is not "IExtension" &&
                                     !IsSettingsInterface(definition))
                .Select(definition => new ConcreteVtable(
                    $"{ToSnakeCase(ExtensionKindName(definition))}_vtable",
                    ShortName(definition.FullName),
                    $"extension_kind::{ExtensionKindName(definition)}",
                    null))
                .ToList();
        }

        public IReadOnlyList<InterfaceDefinition> InterfacesWithGuid { get; }

        public ConcreteVtable HostVtable { get; }

        public IReadOnlyList<ConcreteVtable> ExtensionVtables { get; }

        public IReadOnlyList<ConcreteVtable> SettingVtables { get; }

        public InterfaceDefinition RequireInterface(string name)
        {
            if (_interfaces.TryGetValue(name, out var definition))
                return definition;

            throw new InvalidOperationException($"Interface '{name}' was not found in PIDL.");
        }

        public IReadOnlyList<InterfaceDefinition> FlattenInterfaces(InterfaceDefinition definition)
        {
            var result = new List<InterfaceDefinition>();
            AppendInterfaceChain(definition, result);
            return result;
        }

        public IReadOnlyList<MethodWithOwner> FlattenMethods(InterfaceDefinition definition)
        {
            return FlattenInterfaces(definition)
                .SelectMany(static owner => owner.Methods.Select(method => new MethodWithOwner(owner, method)))
                .ToList();
        }

        private void AppendInterfaceChain(InterfaceDefinition definition, List<InterfaceDefinition> result)
        {
            if (definition.Inherits is not null)
                AppendInterfaceChain(RequireInterface(definition.Inherits), result);

            result.Add(definition);
        }

        private bool IsSettingsInterface(InterfaceDefinition definition)
        {
            return FlattenInterfaces(definition).Any(static value => ShortName(value.FullName) is "ISettingsExtension") &&
                   ShortName(definition.FullName) is not "ISettingsExtension";
        }

        private static bool IsSdkAbstract(InterfaceDefinition definition)
        {
            return definition.Attributes.Any(static attribute => attribute.Name is "sdkAbstract");
        }

        private static string SettingsKindName(InterfaceDefinition definition)
        {
            return SettingNameMappingFor(definition.FullName).KindName;
        }

        private static string ExtensionKindName(InterfaceDefinition definition)
        {
            return ToSnakeCase(InterfaceStem(definition.FullName, ExtensionSuffix));
        }
    }

    private sealed record ConcreteVtable(string Name, string InterfaceName, string? ExtensionKind, string? SettingKind);

    private sealed record SettingNameMapping(string KindName, string ValueThunkPrefix, string? SpecialThunkPrefix = null)
    {
        public string SpecializedThunkPrefix => SpecialThunkPrefix ?? ValueThunkPrefix;
    }

    private sealed record MethodWithOwner(InterfaceDefinition Owner, MethodDefinition Method);
}
