using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Pixeval.Extensions.Generator.Models;

namespace Pixeval.Extensions.Generator;

internal static class CppEmitter
{
    public static string EmitCommon(PidlModel model)
    {
        var context = new CppModelContext(model);
        var builder = new StringBuilder();
        _ = builder.AppendLine(
            """
            // <auto-generated />
            #pragma once
            #include <pixeval/detail/runtime.hpp>

            namespace pixeval::extensions
            {
            """);
        AppendAbiConfiguration(builder, model);
        AppendIids(builder, context);
        AppendEnums(builder, model);
        AppendSlots(builder, context);
        AppendSupportFunctions(builder, context);
        _ = builder.AppendLine("}");
        return builder.ToString();
    }

    public static string EmitSdk(PidlModel model)
    {
        var context = new CppModelContext(model);
        var builder = new StringBuilder();
        _ = builder.AppendLine(
            """
            // <auto-generated />
            #pragma once

            namespace pixeval::extensions
            {
            """);

        AppendVtableDeclarations(builder, context);
        AppendSdkClasses(builder, context, model);
        _ = builder.AppendLine("namespace detail");
        _ = builder.AppendLine("{");
        AppendDefaultValues(builder, model);
        _ = builder.Append(EmitVtables(context));
        _ = builder.AppendLine("}");
        _ = builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendVtableDeclarations(StringBuilder builder, CppModelContext context)
    {
        _ = builder.AppendLine(
            """
            namespace detail
            {
            """);
        _ = builder.AppendLine($"extern void* {context.HostVtable.Name}[];");
        foreach (var vtable in context.SdkVtables)
            _ = builder.AppendLine($"extern void* {vtable.Name}[];");
        _ = builder.AppendLine(
            """
            }

            """);
    }

    private static void AppendSdkClasses(StringBuilder builder, CppModelContext context, PidlModel model)
    {
        foreach (var definition in OrderCppSdkDefinitions(context, model))
            AppendSdkClass(builder, context, definition);
    }

    private static IReadOnlyList<InterfaceDefinition> OrderCppSdkDefinitions(CppModelContext context, PidlModel model)
    {
        var definitions = model.Interfaces
            .Where(static definition => definition.SdkName is not null)
            .ToList();
        var pending = definitions.ToHashSet();
        var ordered = new List<InterfaceDefinition>();

        while (pending.Count > 0)
        {
            var added = false;
            foreach (var definition in pending.ToList())
            {
                var baseInterface = context.ResolveSdkBaseInterface(definition);
                if (baseInterface is not null && pending.Contains(baseInterface))
                    continue;

                ordered.Add(definition);
                _ = pending.Remove(definition);
                added = true;
            }

            if (!added)
                throw new InvalidOperationException("A cycle was found in C++ SDK base definitions.");
        }

        return ordered;
    }

    private static void AppendSdkClass(StringBuilder builder, CppModelContext context, InterfaceDefinition definition)
    {
        var className = definition.SdkName!;
        var baseClass = CppSdkBaseClass(context, definition);
        var methods = CppSdkMethods(context, definition).ToList();
        var properties = BuildCppSdkProperties(methods);
        var handled = new HashSet<MethodDefinition>();
        _ = builder.AppendLine($"class {className} : public {baseClass}");
        _ = builder.AppendLine("{");
        _ = builder.AppendLine("protected:");
        AppendSdkConstructor(builder, context, definition, className);
        _ = builder.AppendLine();
        _ = builder.AppendLine("public:");
        _ = builder.AppendLine($"    virtual ~{className}() = default;");

        foreach (var method in methods)
        {
            if (handled.Contains(method.Method))
                continue;

            if (method.Method.PropertyAccessor is not PropertyAccessorKind.None)
            {
                var property = properties[method.Method.Property!.Name];
                AppendCppSdkProperty(builder, property);
                if (property.Getter is { } getter)
                    _ = handled.Add(getter.Method);
                if (property.Setter is { } setter)
                    _ = handled.Add(setter.Method);
                continue;
            }

            if (method.Method.IsAsyncResultGetter)
            {
                _ = handled.Add(method.Method);
                continue;
            }

            AppendCppSdkMethod(builder, method, FindAsyncResultGetter(methods, method.Method));
            _ = handled.Add(method.Method);
        }

        AppendCppSdkAsyncResultStorage(builder, methods);

        _ = builder.AppendLine("};");
        _ = builder.AppendLine();
    }

    private static string CppSdkBaseClass(CppModelContext context, InterfaceDefinition definition)
    {
        return context.ResolveSdkBaseInterface(definition)?.SdkName ?? "PixevalComObject";
    }

    private static IEnumerable<MethodWithOwner> CppSdkMethods(CppModelContext context, InterfaceDefinition definition)
    {
        var baseInterface = context.ResolveSdkBaseInterface(definition);
        var inherited = baseInterface is null
            ? []
            : context.FlattenInterfaces(baseInterface).ToHashSet();
        return context.FlattenMethods(definition).Where(method => !inherited.Contains(method.Owner));
    }

    private static void AppendSdkConstructor(StringBuilder builder, CppModelContext context, InterfaceDefinition definition, string className)
    {
        var baseInterface = context.ResolveSdkBaseInterface(definition);
        var baseClass = baseInterface?.SdkName ?? "PixevalComObject";
        _ = builder.AppendLine($"    explicit {className}(void** vtable, detail::supports_interface_fn supports_interface) : {baseClass}(vtable, supports_interface) {{}}");
        _ = builder.AppendLine($"    {className}() : {className}(detail::{AbiName(definition)}_vtable, &abi::supports_{AbiName(definition)}) {{}}");
    }

    private static IReadOnlyDictionary<string, CppSdkProperty> BuildCppSdkProperties(IReadOnlyList<MethodWithOwner> methods)
    {
        var properties = new Dictionary<string, CppSdkProperty>(StringComparer.Ordinal);
        foreach (var method in methods.Where(static method => method.Method.PropertyAccessor is not PropertyAccessorKind.None))
        {
            var name = method.Method.Property!.Name;
            if (!properties.TryGetValue(name, out var property))
            {
                property = new CppSdkProperty(method.Method.Property!);
                properties.Add(name, property);
            }

            switch (method.Method.PropertyAccessor)
            {
                case PropertyAccessorKind.Getter:
                    property.Getter = method;
                    break;
                case PropertyAccessorKind.Setter:
                    property.Setter = method;
                    break;
            }
        }

        return properties;
    }

    private static void AppendCppSdkProperty(StringBuilder builder, CppSdkProperty property)
    {
        var name = ToSnakeCase(property.Name);
        var type = CppSdkPropertyType(property);
        var overrideSuffix = CppOverrideSuffix(property);
        if (property.DefaultValue is { } defaultValue)
        {
            if (property.Getter is null)
                throw new InvalidOperationException($"Property '{property.Name}' declares a default value without a getter.");

            _ = builder.AppendLine($"    [[nodiscard]] virtual {type} {name}() const{overrideSuffix} {{ return {CppSdkDefaultValue(defaultValue, property.Getter.Method)}; }}");
        }
        else if (property.Getter is not null)
        {
            _ = builder.AppendLine($"    [[nodiscard]] virtual {type} {name}() const{overrideSuffix} = 0;");
        }

        if (property.Setter is not null)
            _ = builder.AppendLine($"    virtual void {name}({type} value){overrideSuffix} = 0;");
    }

    private static string CppOverrideSuffix(CppSdkProperty property)
    {
        if (!property.IsOverride)
            return "";

        return property.IsSealed ? " override final" : " override";
    }

    private static void AppendCppSdkMethod(StringBuilder builder, MethodWithOwner method, MethodWithOwner? asyncResultGetter)
    {
        var returnType = CppSdkMethodReturnType(method.Method, asyncResultGetter?.Method);
        var name = ToSnakeCase(method.Method.Name);
        var parameters = string.Join(", ", CppSdkParameters(method.Method, skipTask: method.Method.IsAsync));
        var suffix = method.Method.IsVirtual ? $" {{ {CppSdkDefaultBody(method.Method, asyncResultGetter?.Method)} }}" : " = 0;";
        var nodiscard = returnType is "void" ? "" : "[[nodiscard]] ";
        _ = builder.AppendLine($"    {nodiscard}virtual {returnType} {name}({parameters}){suffix}");
    }

    private static void AppendCppSdkAsyncResultStorage(StringBuilder builder, IReadOnlyList<MethodWithOwner> methods)
    {
        var resultGetters = methods.Where(static method => method.Method.IsAsyncResultGetter).ToList();
        if (resultGetters.Count is 0)
            return;

        _ = builder.AppendLine();
        foreach (var resultGetter in resultGetters)
        {
            var type = CppSdkReturnType(resultGetter.Method);
            var stem = GetAsyncResultFieldStem(resultGetter.Method.Name);
            var fieldName = ToSnakeCase(stem) + "_";
            var accessorName = ToSnakeCase(stem) + "_value";
            var setterName = "set_" + ToSnakeCase(stem) + "_value";
            _ = builder.AppendLine($"    void {setterName}({type} value) {{ {fieldName} = std::move(value); }}");
            _ = builder.AppendLine($"    [[nodiscard]] const {type}& {accessorName}() const noexcept {{ return {fieldName}; }}");
            _ = builder.AppendLine($"    {type} {fieldName}{{}};");
        }
    }

    private static string CppSdkPropertyType(CppSdkProperty property)
    {
        if (property.Getter is { } getter)
            return CppSdkReturnType(getter.Method);

        return CppSdkSetterValueType(property.Setter!.Method);
    }

    private static string CppSdkSetterValueType(MethodDefinition method)
    {
        if (method.DictionaryParameters is [{ } dictionary])
            return CppSdkDictionaryType(dictionary);

        if (method.DateTimeOffsetParameters.Count is > 0)
            return "DateTimeOffsetValue";

        var value = method.Parameters.First(static parameter => !parameter.IsGeneratedArrayCount);
        return value.ArrayCountName is null ? CppSdkType(value.Type) : CppSdkArrayType(value.Type);
    }

    private static string CppSdkMethodReturnType(MethodDefinition method, MethodDefinition? asyncResultGetter)
    {
        if (method.IsAsync)
        {
            var resultType = asyncResultGetter is null ? "void" : CppSdkReturnType(asyncResultGetter);
            return resultType is "void" ? "task<void>" : $"task<{resultType}>";
        }

        return CppSdkReturnType(method);
    }

    private static string CppSdkReturnType(MethodDefinition method)
    {
        if (method.ReturnDictionary is { } dictionary)
            return CppSdkDictionaryType(dictionary);

        if (method.ReturnDateTimeOffset is not null)
            return "DateTimeOffsetValue";

        if (method.ReturnArrayCountName is not null)
            return CppSdkArrayType(method.ReturnType);

        return method.ReturnType is "void" ? "void" : CppSdkType(method.ReturnType);
    }

    private static IEnumerable<string> CppSdkParameters(MethodDefinition method, bool skipTask)
    {
        var start = skipTask ? 1 : 0;
        for (var i = start; i < method.Parameters.Count; ++i)
        {
            if (TryMatchDictionaryExpansion(method, i, out var dictionary))
            {
                yield return $"{CppSdkDictionaryType(dictionary)} {ToSnakeCase(dictionary.Name)}";
                ++i;
                continue;
            }

            if (TryMatchDateTimeOffsetExpansion(method, i, out var dateTimeOffset))
            {
                yield return $"DateTimeOffsetValue {ToSnakeCase(dateTimeOffset.Name)}";
                ++i;
                continue;
            }

            var parameter = method.Parameters[i];
            if (parameter.IsGeneratedArrayCount)
                continue;

            var type = parameter.ArrayCountName is null ? CppSdkType(parameter.Type) : CppSdkArrayType(parameter.Type);
            yield return $"{type} {ToSnakeCase(parameter.Name)}";
        }
    }

    private static string CppSdkDictionaryType(DictionaryExpansion dictionary)
    {
        return $"std::vector<std::pair<{CppSdkType(dictionary.KeyType)}, {CppSdkType(dictionary.ValueType)}>>";
    }

    private static string CppSdkArrayType(string type)
    {
        var elementType = ElementType(type);
        return elementType switch
        {
            "byte" => "std::vector<std::uint8_t>",
            _ => $"std::vector<{CppSdkType(elementType)}>"
        };
    }

    private static string CppSdkType(string type)
    {
        return type switch
        {
            "bool" => "bool",
            "byte" => "std::uint8_t",
            "short" => "std::int16_t",
            "ushort" => "std::uint16_t",
            "int" => "std::int32_t",
            "uint" => "std::uint32_t",
            "long" => "std::int64_t",
            "ulong" => "std::uint64_t",
            "double" => "double",
            "string" => "std::u16string",
            "string?" => "std::optional<std::u16string>",
            "IStream" => "Stream",
            "IProgressNotifier" => "ProgressNotifier",
            "ITaskCompletionSource" => "TaskCompletionSource",
            _ => ShortName(type)
        };
    }

    private static string CppSdkDefaultValue(string value, MethodDefinition method)
    {
        var literal = value.Trim();
        if (literal is "null")
            return "std::nullopt";
        if (literal is "default")
            return $"{CppSdkReturnType(method)}{{}}";

        return PidlDefaultValueFormatter.Cpp(literal, method.Property?.Type ?? method.ReturnType);
    }

    private static string CppSdkDefaultBody(MethodDefinition method, MethodDefinition? asyncResultGetter)
    {
        if (method.ReturnType is "void" && !method.IsAsync)
            return "";
        if (method.IsAsync)
        {
            if (asyncResultGetter is null)
                return "co_return;";

            return $"co_return {CppSdkImplicitDefaultValue(CppSdkReturnType(asyncResultGetter))};";
        }

        return $"return {CppSdkImplicitDefaultValue(CppSdkReturnType(method))};";
    }

    private static string CppSdkImplicitDefaultValue(string type)
    {
        return type switch
        {
            "void" => "",
            "bool" => "false",
            _ => $"{type}{{}}"
        };
    }

    private static MethodWithOwner? FindAsyncResultGetter(IReadOnlyList<MethodWithOwner> methods, MethodDefinition taskMethod)
    {
        return methods.FirstOrDefault(method => ReferenceEquals(method.Method.AsyncResultGetter?.SourceMethod, taskMethod));
    }

    private static string GetAsyncResultFieldStem(string methodName)
    {
        if (methodName.Length > 3 &&
            methodName.StartsWith("Get", StringComparison.Ordinal))
            return methodName[3..];

        return methodName;
    }

    private static bool TryMatchDateTimeOffsetExpansion(MethodDefinition method, int index, out DateTimeOffsetExpansion dateTimeOffset)
    {
        dateTimeOffset = null!;
        if (index + 1 >= method.Parameters.Count)
            return false;

        var ticks = method.Parameters[index];
        var offset = method.Parameters[index + 1];
        var match = method.DateTimeOffsetParameters.FirstOrDefault(expansion =>
            expansion.TicksName == ticks.Name &&
            expansion.OffsetName == offset.Name);
        if (match is null)
            return false;

        dateTimeOffset = match;
        return true;
    }

    private static bool TryMatchDictionaryExpansion(MethodDefinition method, int index, out DictionaryExpansion dictionary)
    {
        dictionary = null!;
        if (index + 1 >= method.Parameters.Count)
            return false;

        var keys = method.Parameters[index];
        var values = method.Parameters[index + 1];
        var match = method.DictionaryParameters.FirstOrDefault(expansion =>
            expansion.KeysName == keys.Name &&
            expansion.ValuesName == values.Name);
        if (match is null)
            return false;

        dictionary = match;
        return true;
    }

    private static void AppendDefaultValues(StringBuilder builder, PidlModel model)
    {
        var appended = false;
        foreach (var definition in model.Interfaces)
        {
            foreach (var property in definition.Properties.Where(static property => property.DefaultValue is not null))
            {
                var type = PidlDefaultValueFormatter.CppType(property.Type, property.DefaultValue!);
                var value = PidlDefaultValueFormatter.Cpp(property.DefaultValue!, property.Type);
                _ = builder.AppendLine($"inline constexpr {type} {DefaultValueConstantName(definition, property)} = {value};");
                appended = true;
            }
        }

        if (appended)
            _ = builder.AppendLine();
    }

    private static void AppendAbiConfiguration(StringBuilder builder, PidlModel model)
    {
        _ = builder.AppendLine(
            $$"""
            namespace abi
            {
                inline constexpr std::u16string_view sdk_version = u"{{model.SdkVersion}}";
                using bool_abi = {{CppBoolAbiType(model.Metadata)}};
                inline constexpr bool_abi bool_false = {{CppBoolFalse(model.Metadata)}};

                [[nodiscard]] inline bool bool_from_abi(bool_abi value) noexcept
                {
                    return {{CppBoolToCpp(model.Metadata, "value")}};
                }

                [[nodiscard]] inline bool_abi bool_to_abi(bool value) noexcept
                {
                    return {{CppBoolFromCpp(model.Metadata, "value")}};
                }
            }

            """);
    }

    private static string CppBoolAbiType(PidlMetadata metadata)
    {
        return metadata.BoolMarshalling switch
        {
            UnmanagedType.Bool => "std::int32_t",
            _ => throw new ArgumentOutOfRangeException(nameof(metadata))
        };
    }

    private static string CppBoolFalse(PidlMetadata metadata)
    {
        return metadata.BoolMarshalling switch
        {
            UnmanagedType.Bool => "0",
            _ => throw new ArgumentOutOfRangeException(nameof(metadata))
        };
    }

    private static string CppBoolFromCpp(PidlMetadata metadata, string expression)
    {
        return metadata.BoolMarshalling switch
        {
            UnmanagedType.Bool => $"({expression} ? 1 : 0)",
            _ => throw new ArgumentOutOfRangeException(nameof(metadata))
        };
    }

    private static string CppBoolToCpp(PidlMetadata metadata, string expression)
    {
        return metadata.BoolMarshalling switch
        {
            UnmanagedType.Bool => $"({expression} != 0)",
            _ => throw new ArgumentOutOfRangeException(nameof(metadata))
        };
    }

    private static string EmitVtables(CppModelContext context)
    {
        var builder = new StringBuilder();
        AppendVtable(builder, context, context.HostVtable);
        foreach (var vtable in context.SdkVtables)
        {
            AppendSdkThunks(builder, context, vtable);
            AppendVtable(builder, context, vtable);
        }

        return builder.ToString();
    }

    private static void AppendIids(StringBuilder builder, CppModelContext context)
    {
        _ = builder.AppendLine(
            """
            namespace abi
            {
                constexpr guid iid_iunknown{0x00000000, 0x0000, 0x0000, {0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46}};
            """);
        foreach (var definition in context.InterfacesWithGuid)
            _ = builder.AppendLine($"    constexpr guid iid_{AbiName(definition)}{FormatGuid(definition.Guid!)};");
        _ = builder.AppendLine(
            """
            }

            """);
    }

    private static void AppendEnums(StringBuilder builder, PidlModel model)
    {
        foreach (var definition in model.Enums)
        {
            _ = builder.AppendLine(
                $$"""
                enum class {{ShortName(definition.FullName)}} : std::int32_t
                {
                """);
            var nextValue = 0;
            foreach (var value in definition.Values)
            {
                var actualValue = value.Value ?? nextValue.ToString();
                _ = builder.AppendLine($"    {value.Name} = {actualValue},");
                if (int.TryParse(actualValue, out var parsed))
                    nextValue = parsed + 1;
                else
                    ++nextValue;
            }

            _ = builder.AppendLine(
                """
                };

                """);
        }
    }

    private static void AppendSlots(StringBuilder builder, CppModelContext context)
    {
        _ = builder.AppendLine(
            """
            namespace abi
            {
            """);
        foreach (var definition in context.InterfacesWithGuid)
        {
            _ = builder.AppendLine(
                $$"""
                    enum class {{AbiName(definition)}}_slot : std::int32_t
                    {
                        query_interface = 0,
                        add_ref = 1,
                        release = 2,
                """);

            var slot = 3;
            foreach (var method in context.FlattenMethods(definition, includeOverrides: false))
                _ = builder.AppendLine($"        {ToSnakeCase(method.Method.Name)} = {slot++},");

            _ = builder.AppendLine(
                """
                    };

                """);
        }

        _ = builder.AppendLine(
            """
            }

            """);
    }

    private static void AppendSupportFunctions(StringBuilder builder, CppModelContext context)
    {
        _ = builder.AppendLine(
            """
            namespace abi
            {
            """);
        foreach (var definition in context.InterfacesWithGuid)
        {
            _ = builder.AppendLine(
                $$"""
                    [[nodiscard]] inline bool supports_{{AbiName(definition)}}(const guid& iid) noexcept
                    {
                """);

            var supported = context.FlattenInterfaces(definition)
                .Where(static value => value.Guid is not null)
                .Select(static value => $"iid_{AbiName(value)}")
                .ToList();

            _ = builder.AppendLine(
                "        return iid == iid_iunknown ||");
            for (var i = 0; i < supported.Count; i++)
            {
                var terminator = i == supported.Count - 1 ? ";" : " ||";
                _ = builder.AppendLine($"               iid == {supported[i]}{terminator}");
            }

            _ = builder.AppendLine(
                """
                    }

                """);
        }

        _ = builder.AppendLine(
            """
            }

            """);
    }

    private static void AppendVtable(StringBuilder builder, CppModelContext context, ConcreteVtable vtable)
    {
        _ = builder.AppendLine(
            $$"""
            inline void* {{vtable.Name}}[] = {
            """);
        _ = builder.AppendLine(
            vtable.IsHost
                ?
                """
                    reinterpret_cast<void*>(&host_query_interface),
                    reinterpret_cast<void*>(&host_add_ref),
                    reinterpret_cast<void*>(&host_release),
                """
                :
                """
                    reinterpret_cast<void*>(&pixeval_query_interface),
                    reinterpret_cast<void*>(&pixeval_add_ref),
                    reinterpret_cast<void*>(&pixeval_release),
                """);

        foreach (var method in context.FlattenMethods(vtable.Definition, includeOverrides: false))
            _ = builder.AppendLine($"    reinterpret_cast<void*>(&{ThunkName(vtable, method)}),");

        TrimLastComma(builder);
        _ = builder.AppendLine(
            """
            };

            """);
    }

    private static void AppendSdkThunks(StringBuilder builder, CppModelContext context, ConcreteVtable vtable)
    {
        var methods = context.FlattenMethods(vtable.Definition).ToList();
        foreach (var method in context.FlattenMethods(vtable.Definition, includeOverrides: false))
            AppendSdkThunk(builder, vtable, method, FindAsyncResultGetter(methods, method.Method));
    }

    private static void AppendSdkThunk(StringBuilder builder, ConcreteVtable vtable, MethodWithOwner method, MethodWithOwner? asyncResultGetter)
    {
        var parameters = string.Join(", ", CppThunkParameters(method.Method));
        var className = vtable.Definition.SdkName!;
        _ = builder.AppendLine(
            $$"""
            inline hresult PIXEV_CALL {{ThunkName(vtable, method)}}({{parameters}})
            {
                auto& instance = static_cast<{{className}}&>(pixeval_owner(self));
            """);
        AppendDictionaryPreparations(builder, method.Method, "    ");

        if (method.Method.IsAsync)
        {
            AppendAsyncThunkBody(builder, method.Method, asyncResultGetter?.Method);
        }
        else if (method.Method.IsAsyncResultGetter)
        {
            var value = $"instance.{ToSnakeCase(GetAsyncResultFieldStem(method.Method.Name))}_value()";
            AppendCopyReturnValue(builder, method.Method, value, "    ");
        }
        else if (method.Method.PropertyAccessor is PropertyAccessorKind.Getter)
        {
            var value = $"instance.{ToSnakeCase(method.Method.Property!.Name)}()";
            AppendCopyReturnValue(builder, method.Method, value, "    ");
        }
        else if (method.Method.PropertyAccessor is PropertyAccessorKind.Setter)
        {
            var value = CppSetterArgument(method.Method);
            _ = builder.AppendLine($"    instance.{ToSnakeCase(method.Method.Property!.Name)}({value});");
            _ = builder.AppendLine("    return S_OK;");
        }
        else if (method.Method.ReturnType is "void")
        {
            _ = builder.AppendLine($"    instance.{ToSnakeCase(method.Method.Name)}({string.Join(", ", CppCallArguments(method.Method, useCapturedNames: false))});");
            _ = builder.AppendLine("    return S_OK;");
        }
        else
        {
            _ = builder.AppendLine($"    auto value = instance.{ToSnakeCase(method.Method.Name)}({string.Join(", ", CppCallArguments(method.Method, useCapturedNames: false))});");
            AppendCopyReturnValue(builder, method.Method, "value", "    ");
        }

        _ = builder.AppendLine("}");
        _ = builder.AppendLine();
    }

    private static IEnumerable<string> CppThunkParameters(MethodDefinition method)
    {
        yield return "void* self";
        foreach (var parameter in method.Parameters)
            yield return $"{CppAbiParameterType(parameter)} {parameter.Name}";
        if (method.ReturnType is not "void")
            yield return $"{CppReturnParameterType(method)} result";
    }

    private static void AppendAsyncThunkBody(StringBuilder builder, MethodDefinition method, MethodDefinition? asyncResultGetter)
    {
        var captures = CppAsyncCaptures(method).ToList();
        var captureList = captures.Count is 0 ? "" : ", " + string.Join(", ", captures);
        _ = builder.AppendLine(
            $$"""
                run_async(
                    self,
                    task,
                    [&instance{{captureList}}]() mutable -> ::pixeval::extensions::task<void>
                    {
            """);
        var call = $"instance.{ToSnakeCase(method.Name)}({string.Join(", ", CppCallArguments(method, useCapturedNames: true))})";
        if (asyncResultGetter is null)
            _ = builder.AppendLine($"            co_await {call};");
        else
            _ = builder.AppendLine($"            instance.set_{ToSnakeCase(GetAsyncResultFieldStem(asyncResultGetter.Name))}_value(co_await {call});");
        _ = builder.AppendLine(
            """
                    });
                return S_OK;
            """);
    }

    private static void AppendDictionaryPreparations(StringBuilder builder, MethodDefinition method, string indent)
    {
        foreach (var dictionary in method.DictionaryParameters)
        {
            var name = ToSnakeCase(dictionary.Name);
            var keys = name + "_keys";
            var values = name + "_values";
            _ = builder.AppendLine(
                $"""
                {indent}auto {keys} = {CppReadArrayExpression(dictionary.KeyType, dictionary.KeysName, dictionary.CountName)};
                {indent}auto {values} = {CppReadArrayExpression(dictionary.ValueType, dictionary.ValuesName, dictionary.CountName)};
                {indent}{CppSdkDictionaryType(dictionary)} {name};
                {indent}{name}.reserve(static_cast<std::size_t>({dictionary.CountName}));
                {indent}for (std::int32_t i = 0; i < {dictionary.CountName}; ++i)
                {indent}    {name}.emplace_back(std::move({keys}[i]), std::move({values}[i]));
                """);
        }
    }

    private static void AppendCopyReturnValue(StringBuilder builder, MethodDefinition method, string value, string indent)
    {
        if (method.ReturnDictionary is { } dictionary)
        {
            AppendCopyReturnDictionary(builder, dictionary, value, indent);
            return;
        }

        if (method.ReturnDateTimeOffset is { } dateTimeOffset)
        {
            _ = builder.AppendLine(
                $"""
                {indent}auto value = {value};
                {indent}if ({dateTimeOffset.TicksName} == nullptr || {dateTimeOffset.OffsetName} == nullptr)
                {indent}    return E_POINTER;
                {indent}*{dateTimeOffset.TicksName} = value.utc_date_time_ticks;
                {indent}*{dateTimeOffset.OffsetName} = value.minutes_offset;
                {indent}return S_OK;
                """);
            return;
        }

        if (method.ReturnArrayCountName is { } countName)
        {
            _ = builder.AppendLine($"{indent}return {CppCopyArrayReturnValue(method.ReturnType, value, countName, "result")};");
            return;
        }

        switch (method.ReturnType)
        {
            case "string":
                _ = builder.AppendLine($"{indent}return abi::copy_utf16({value}, result);");
                return;
            case "string?":
                _ = builder.AppendLine($"{indent}return abi::copy_optional_utf16({value}, result);");
                return;
            case "bool":
                AppendScalarReturn(builder, $"abi::bool_to_abi({value})", indent);
                return;
            case "double":
                AppendScalarReturn(builder, value, indent);
                return;
            case "uint":
                AppendScalarReturn(builder, value, indent);
                return;
            case "Symbol":
                AppendScalarReturn(builder, $"static_cast<std::int32_t>({value})", indent);
                return;
            case "IStream":
                _ = builder.AppendLine(
                    $"""
                    {indent}if (result == nullptr)
                    {indent}    return E_POINTER;
                    {indent}*result = {value}.native();
                    {indent}return S_OK;
                    """);
                return;
            default:
                if (method.ReturnType.EndsWith("Type", StringComparison.Ordinal))
                    AppendScalarReturn(builder, $"static_cast<std::int32_t>({value})", indent);
                else
                    AppendScalarReturn(builder, value, indent);
                return;
        }
    }

    private static void AppendCopyReturnDictionary(StringBuilder builder, DictionaryExpansion dictionary, string value, string indent)
    {
        var keys = "return_keys_values";
        var values = "return_values_values";
        _ = builder.AppendLine(
            $$"""
            {{indent}}auto values = {{value}};
            {{indent}}std::vector<{{CppSdkType(dictionary.KeyType)}}> {{keys}};
            {{indent}}std::vector<{{CppSdkType(dictionary.ValueType)}}> {{values}};
            {{indent}}{{keys}}.reserve(values.size());
            {{indent}}{{values}}.reserve(values.size());
            {{indent}}for (const auto& item : values)
            {{indent}}{
            {{indent}}    {{keys}}.push_back(item.first);
            {{indent}}    {{values}}.push_back(item.second);
            {{indent}}}
            {{indent}}auto hr = {{CppCopyArrayReturnValue(dictionary.KeyType + "[]", keys, dictionary.CountName, dictionary.KeysName)}};
            {{indent}}if (hr != S_OK)
            {{indent}}    return hr;
            {{indent}}hr = {{CppCopyArrayReturnValue(dictionary.ValueType + "[]", values, "nullptr", dictionary.ValuesName)}};
            {{indent}}if (hr != S_OK)
            {{indent}}{
            """);
        if (dictionary.KeyType is "string")
        {
            _ = builder.AppendLine($"{indent}    free_string_array(*{dictionary.KeysName}, *{dictionary.CountName});");
            _ = builder.AppendLine($"{indent}    *{dictionary.KeysName} = nullptr;");
        }
        _ = builder.AppendLine(
            $$"""
            {{indent}}    *{{dictionary.CountName}} = 0;
            {{indent}}    return hr;
            {{indent}}}
            {{indent}}return S_OK;
            """);
    }

    private static void AppendScalarReturn(StringBuilder builder, string value, string indent)
    {
        _ = builder.AppendLine(
            $"""
            {indent}if (result == nullptr)
            {indent}    return E_POINTER;
            {indent}*result = {value};
            {indent}return S_OK;
            """);
    }

    private static string CppAbiParameterType(ParameterDefinition parameter)
    {
        if (parameter.ArrayCountName is not null)
            return CppAbiArrayType(ElementType(parameter.Type), parameter.IsOut);

        var type = parameter.IsOut
            ? CppAbiOutScalarType(parameter.Type)
            : CppAbiInScalarType(parameter.Type);
        return parameter.IsOut ? type + "*" : type;
    }

    private static string CppReturnParameterType(MethodDefinition method)
    {
        return method.ReturnArrayCountName is not null
            ? CppAbiArrayType(ElementType(method.ReturnType), isOut: true)
            : CppAbiOutScalarType(method.ReturnType) + "*";
    }

    private static string CppAbiArrayType(string elementType, bool isOut)
    {
        var arrayType = elementType switch
        {
            "byte" => "std::uint8_t*",
            "int" => "std::int32_t*",
            "uint" => "std::uint32_t*",
            "string" or "IStream" => "void**",
            _ when IsInterfaceType(elementType) => "void**",
            _ => CppAbiInScalarType(elementType) + "*"
        };
        return isOut ? arrayType + "*" : arrayType;
    }

    private static string CppAbiInScalarType(string type)
    {
        return type switch
        {
            "bool" => "abi::bool_abi",
            "byte" => "std::uint8_t",
            "short" => "std::int16_t",
            "ushort" => "std::uint16_t",
            "int" => "std::int32_t",
            "uint" => "std::uint32_t",
            "long" => "std::int64_t",
            "ulong" => "std::uint64_t",
            "double" => "double",
            "string" or "string?" => "const utf16_char*",
            "IStream" or "IProgressNotifier" or "ITaskCompletionSource" => "void*",
            _ when IsInterfaceType(type) => "void*",
            _ => ShortName(type)
        };
    }

    private static string CppAbiOutScalarType(string type)
    {
        return type switch
        {
            "bool" => "abi::bool_abi",
            "byte" => "std::uint8_t",
            "short" => "std::int16_t",
            "ushort" => "std::uint16_t",
            "int" or "Symbol" => "std::int32_t",
            "uint" => "std::uint32_t",
            "long" => "std::int64_t",
            "ulong" => "std::uint64_t",
            "double" => "double",
            "string" or "string?" => "utf16_char*",
            "IStream" or "IProgressNotifier" or "ITaskCompletionSource" => "void*",
            _ when type.EndsWith("Type", StringComparison.Ordinal) => "std::int32_t",
            _ when IsInterfaceType(type) => "void*",
            _ => ShortName(type)
        };
    }

    private static string CppSetterArgument(MethodDefinition method)
    {
        if (method.DictionaryParameters is [{ } dictionary])
            return ToSnakeCase(dictionary.Name);
        if (method.DateTimeOffsetParameters is [{ } dateTimeOffset])
            return $"DateTimeOffsetValue{{{dateTimeOffset.TicksName}, {dateTimeOffset.OffsetName}}}";

        var value = method.Parameters.First(static parameter => !parameter.IsGeneratedArrayCount);
        return CppReadArgument(value);
    }

    private static IEnumerable<string> CppCallArguments(MethodDefinition method, bool useCapturedNames)
    {
        var start = method.IsAsync ? 1 : 0;
        for (var i = start; i < method.Parameters.Count; ++i)
        {
            if (TryMatchDictionaryExpansion(method, i, out var dictionary))
            {
                yield return ToSnakeCase(dictionary.Name);
                ++i;
                continue;
            }

            if (TryMatchDateTimeOffsetExpansion(method, i, out var dateTimeOffset))
            {
                yield return useCapturedNames
                    ? ToSnakeCase(dateTimeOffset.Name)
                    : $"DateTimeOffsetValue{{{dateTimeOffset.TicksName}, {dateTimeOffset.OffsetName}}}";
                ++i;
                continue;
            }

            var parameter = method.Parameters[i];
            if (parameter.IsGeneratedArrayCount)
                continue;

            yield return useCapturedNames ? ToSnakeCase(parameter.Name) : CppReadArgument(parameter);
        }
    }

    private static IEnumerable<string> CppAsyncCaptures(MethodDefinition method)
    {
        for (var i = 1; i < method.Parameters.Count; ++i)
        {
            if (TryMatchDictionaryExpansion(method, i, out var dictionary))
            {
                var name = ToSnakeCase(dictionary.Name);
                yield return $"{name} = std::move({name})";
                ++i;
                continue;
            }

            if (TryMatchDateTimeOffsetExpansion(method, i, out var dateTimeOffset))
            {
                yield return $"{ToSnakeCase(dateTimeOffset.Name)} = DateTimeOffsetValue{{{dateTimeOffset.TicksName}, {dateTimeOffset.OffsetName}}}";
                ++i;
                continue;
            }

            var parameter = method.Parameters[i];
            if (parameter.IsGeneratedArrayCount)
                continue;

            yield return $"{ToSnakeCase(parameter.Name)} = {CppReadArgument(parameter)}";
        }
    }

    private static string CppReadArgument(ParameterDefinition parameter)
    {
        if (parameter.ArrayCountName is { } countName)
            return CppReadArrayExpression(ElementType(parameter.Type), parameter.Name, countName);

        return parameter.Type switch
        {
            "string" or "string?" => $"abi::to_u16string({parameter.Name})",
            "bool" => $"abi::bool_from_abi({parameter.Name})",
            "IStream" => $"Stream{{{parameter.Name}}}",
            "IProgressNotifier" => $"ProgressNotifier{{{parameter.Name}}}",
            "ITaskCompletionSource" => $"TaskCompletionSource{{{parameter.Name}}}",
            _ when IsInterfaceType(parameter.Type) => parameter.Name,
            _ => parameter.Name
        };
    }

    private static string CppReadArrayExpression(string elementType, string values, string count)
    {
        return elementType switch
        {
            "string" => $"detail::read_string_array({values}, {count})",
            "int" => $"detail::read_int32_array({values}, {count})",
            "IStream" => $"detail::read_stream_array({values}, {count})",
            _ => $"std::vector<{CppSdkType(elementType)}>({values}, {values} + {count})"
        };
    }

    private static string CppCopyArrayReturnValue(string returnType, string value, string count, string result)
    {
        return ElementType(returnType) switch
        {
            "string" => $"detail::copy_string_array({value}, {count}, {result})",
            "int" => $"detail::copy_int32_array({value}, {count}, {result})",
            "byte" => $"detail::copy_byte_array({value}, {count}, {result})",
            _ => throw new InvalidOperationException($"Unsupported C++ SDK array return type: {returnType}")
        };
    }

    private static bool IsInterfaceType(string type)
    {
        return type.Length > 1 &&
               type[0] is 'I' &&
               char.IsUpper(type[1]) &&
               !type.EndsWith("[]", StringComparison.Ordinal);
    }

    private static string ThunkName(ConcreteVtable vtable, MethodWithOwner method)
    {
        return vtable.IsHost
            ? $"host_{ToSnakeCase(method.Method.Name)}"
            : $"{AbiName(vtable.Definition)}_{ToSnakeCase(method.Method.Name)}";
    }

    private static string FormatGuid(string value)
    {
        var parts = Guid.Parse(value).ToString("D").Split('-');
        var data4 = parts[3] + parts[4];
        var bytes = Enumerable.Range(0, 8)
            .Select(index => "0x" + data4.Substring(index * 2, 2).ToUpperInvariant());

        return $"{{0x{parts[0].ToUpperInvariant()}, 0x{parts[1].ToUpperInvariant()}, 0x{parts[2].ToUpperInvariant()}, {{{string.Join(", ", bytes)}}}}}";
    }

    private static string AbiName(InterfaceDefinition definition)
    {
        var name = ShortName(definition.FullName);
        if (name.StartsWith('I') && name.Length > 1 && char.IsUpper(name[1]))
            name = name[1..];

        return ToSnakeCase(name);
    }

    private static string DefaultValueConstantName(InterfaceDefinition definition, PropertyDefinition property)
    {
        return $"default_{AbiName(definition)}_{ToSnakeCase(property.Name)}";
    }

    private static string ToSnakeCase(string value)
    {
        var builder = new StringBuilder();
        for (var i = 0; i < value.Length; i++)
        {
            var current = value[i];
            if (char.IsUpper(current) && i > 0)
                _ = builder.Append('_');
            _ = builder.Append(char.ToLowerInvariant(current));
        }

        return builder.ToString();
    }

    private static string ElementType(string type)
    {
        if (type.EndsWith("[]?", StringComparison.Ordinal))
            return type[..^3];

        return type.EndsWith("[]", StringComparison.Ordinal) ? type[..^2] : type;
    }

    private static string ShortName(string fullName)
    {
        var separator = fullName.LastIndexOf('.');
        return separator < 0 ? fullName : fullName[(separator + 1)..];
    }

    private static void TrimLastComma(StringBuilder builder)
    {
        for (var i = builder.Length - 1; i >= 0; i--)
        {
            if (builder[i] is not ',')
                continue;

            _ = builder.Remove(i, 1);
            return;
        }
    }

    private sealed class CppModelContext
    {
        private readonly Dictionary<string, InterfaceDefinition> _interfaces;

        public CppModelContext(PidlModel model)
        {
            _interfaces = model.Interfaces
                .SelectMany(static definition => new[]
                {
                    new KeyValuePair<string, InterfaceDefinition>(definition.FullName, definition),
                    new KeyValuePair<string, InterfaceDefinition>(ShortName(definition.FullName), definition)
                })
                .GroupBy(static pair => pair.Key, StringComparer.Ordinal)
                .ToDictionary(static group => group.Key, static group => group.First().Value, StringComparer.Ordinal);

            InterfacesWithGuid = model.Interfaces.Where(static definition => definition.Guid is not null).ToList();
            HostVtable = new ConcreteVtable("host_vtable", RequireInterface("IExtensionsHost"), IsHost: true);
            SdkVtables = model.Interfaces
                .Where(static definition => definition.SdkName is not null)
                .Select(static definition => new ConcreteVtable($"{AbiName(definition)}_vtable", definition, IsHost: false))
                .ToList();
        }

        public IReadOnlyList<InterfaceDefinition> InterfacesWithGuid { get; }

        public ConcreteVtable HostVtable { get; }

        public IReadOnlyList<ConcreteVtable> SdkVtables { get; }

        public InterfaceDefinition RequireInterface(string name)
        {
            if (_interfaces.TryGetValue(name, out var definition))
                return definition;

            throw new InvalidOperationException($"Interface '{name}' was not found in PIDL.");
        }

        public InterfaceDefinition? ResolveSdkBaseInterface(InterfaceDefinition definition)
        {
            if (definition.Inherits is null)
                return null;

            var current = RequireInterface(definition.Inherits);
            while (true)
            {
                if (current.SdkName is not null)
                    return current;

                if (current.Inherits is null)
                    return null;

                current = RequireInterface(current.Inherits);
            }
        }

        public IReadOnlyList<InterfaceDefinition> FlattenInterfaces(InterfaceDefinition definition)
        {
            var result = new List<InterfaceDefinition>();
            AppendInterfaceChain(definition, result);
            return result;
        }

        public IReadOnlyList<MethodWithOwner> FlattenMethods(InterfaceDefinition definition, bool includeOverrides = true)
        {
            return FlattenInterfaces(definition)
                .SelectMany(static owner => owner.Methods.Select(method => new MethodWithOwner(owner, method)))
                .Where(method => includeOverrides || !method.Method.IsOverride)
                .ToList();
        }

        private void AppendInterfaceChain(InterfaceDefinition definition, List<InterfaceDefinition> result)
        {
            if (definition.Inherits is not null)
                AppendInterfaceChain(RequireInterface(definition.Inherits), result);

            result.Add(definition);
        }

    }

    private sealed record ConcreteVtable(string Name, InterfaceDefinition Definition, bool IsHost);

    private sealed class CppSdkProperty(PropertyDefinition definition)
    {
        public string Name { get; } = definition.Name;

        public string? DefaultValue { get; } = definition.DefaultValue;

        public bool IsOverride => Getter?.Method.IsOverride is true || Setter?.Method.IsOverride is true;

        public bool IsSealed => Getter?.Method.IsSealed is true || Setter?.Method.IsSealed is true;

        public MethodWithOwner? Getter { get; set; }

        public MethodWithOwner? Setter { get; set; }
    }

    private sealed record MethodWithOwner(InterfaceDefinition Owner, MethodDefinition Method);
}
