using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Pixeval.Extensions.Generator.Models;

namespace Pixeval.Extensions.Generator;

internal static class CSharpEmitterSupport
{
    private static readonly string[] _CommonRuntimeNamespaces =
    [
        "System",
        "System.Collections.Generic",
        "System.ComponentModel",
        "System.IO",
        "System.Linq",
        "System.Runtime.InteropServices",
        "System.Runtime.InteropServices.Marshalling",
        "System.Threading.Tasks",
        "FluentIcons.Common"
    ];

    private static readonly string[] _SdkRuntimeNamespaces =
    [
        "System",
        "System.Collections.Generic",
        "System.Globalization",
        "System.IO",
        "System.Linq",
        "System.Runtime.InteropServices",
        "System.Runtime.InteropServices.Marshalling",
        "System.Threading.Tasks",
        "FluentIcons.Common"
    ];

    public static void AppendHeader(StringBuilder builder, IEnumerable<string> namespaces)
    {
        _ = builder.AppendLine(
            """
            // <auto-generated />
            #nullable enable
            #pragma warning disable CS1591

            """);

        foreach (var namespaceName in DistinctNamespaces(namespaces))
            _ = builder.AppendLine($"using {namespaceName};");

        _ = builder.AppendLine();
    }

    public static IEnumerable<string> CommonNamespaces(PidlModel model)
    {
        return _CommonRuntimeNamespaces.Concat(ModelNamespaces(model));
    }

    public static IEnumerable<string> SdkNamespaces(PidlModel model)
    {
        return _SdkRuntimeNamespaces
            .Concat(ModelNamespaces(model))
            .Concat(model.Interfaces
                .Where(static definition => definition.SdkName is not null)
                .Select(static definition => SdkNamespace(definition.FullName)));
    }

    private static IEnumerable<string> ModelNamespaces(PidlModel model)
    {
        return model.Enums.Select(static definition => NamespaceOf(definition.FullName))
            .Concat(model.Interfaces.Select(static definition => NamespaceOf(definition.FullName)));
    }

    private static IEnumerable<string> DistinctNamespaces(IEnumerable<string> namespaces)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var namespaceName in namespaces)
        {
            if (string.IsNullOrWhiteSpace(namespaceName) || !seen.Add(namespaceName))
                continue;

            yield return namespaceName;
        }
    }

    private static string SdkNamespace(string fullName)
    {
        const string sourcePrefix = "Pixeval.Extensions.Common";
        const string targetPrefix = "Pixeval.Extensions.SDK";

        var sourceNamespace = NamespaceOf(fullName);
        if (!sourceNamespace.StartsWith(sourcePrefix, StringComparison.Ordinal))
            return targetPrefix;

        var suffix = sourceNamespace[sourcePrefix.Length..];
        if (suffix.StartsWith(".Commands", StringComparison.Ordinal))
            suffix = suffix[".Commands".Length..];

        return targetPrefix + suffix;
    }

    private static string NamespaceOf(string fullName)
    {
        var separator = fullName.LastIndexOf('.');
        return separator < 0 ? "" : fullName[..separator];
    }
}
